### ISSUE TITLE
Window not scrollable

### ISSUE THREAD

**Issue by wwhsiao** [phac-nml/irida#1]
After selecting samples and pipeline to run, if the browser window is too narrow, the Ready to Launch button gets pushed to the bottom of the screen and the browser is not scrollable.  As a result, one might miss the launch button.  I tested this on Chrome.

**Comment by joshsadam** [comment]
This has been fixed in commit ed588d7e80dfa252806de509c791f253a78473e2 and will be available in the 1.1.0 release.
