### ISSUE TITLE
Frontend: Missing Gruntfile

### ISSUE THREAD

**Issue by dfornika** [phac-nml/irida#10]
The `grunt build` step in the `updateDevDependencies.sh` script fails because there is not `Gruntfile` in the repo.

Steps to reproduce:

```
cd src/main/webapp
bash ../../../scripts/updateDevDependencies.sh
cat ~/.irida-npm/frontend-init.log
```

Result:

```
A valid Gruntfile could not be found. Please see the getting started guide for
more information on how to configure grunt: http://gruntjs.com/getting-started
Fatal error: Unable to find Gruntfile.
```

**Comment by joshsadam** [comment]
Hi Dan,

Thanks for letting me know about this error.  I removed grunt a while ago and this script was missed in the update. You should not need to run this script at all, just run the web server and it will do this for you.

Josh
