### ISSUE TITLE
User Account Page > multiple listings for same project if project member & group member on project

### ISSUE THREAD

**Issue by joshsadam** [phac-nml/irida#1000]
## Describe the bug
If a user is both a member of a project and a member of a group that is on the project, the project will be displayed twice in their projects table.

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Add a user to a project
2. Add the user to a group 
3. Add the group to the project
4. Go to the user account page and the project is listed twixt

## Expected behaviour
Project listed once with the highest level role

## Additional context
Additional information to help solve the problem.  Test files, screenshots, IRIDA version information can go here.

**Comment by ksierks** [comment]
Fixed in #1248.
