### ISSUE TITLE
Update breadcrumbs

### ISSUE THREAD

**Issue by joshsadam** [phac-nml/irida#101]
Current breadcrumbs 

![image](https://user-images.githubusercontent.com/8951708/52304882-5a943000-2959-11e9-9a8c-d5a9c5024869.png)

TO be:

![image](https://user-images.githubusercontent.com/8951708/52304894-641d9800-2959-11e9-8283-0523666abdb5.png)

Were the name is there instead of the id.

This was a suggestion by Gary.

Imported from GitLab issue #496.  Originally posted on 2017/07/05 03:15PM

**Comment by tom114** [comment]
Need much more description here.

Imported from GitLab.  Originally posted on 2017/08/29 11:03AM

**Comment by ericenns** [comment]
Fixed in #599
