### ISSUE TITLE
Synchronization buttons greyed out when Sync'd project is in the "unsynchronized" state

### ISSUE THREAD

**Issue by JeffreyThiessen** [phac-nml/irida#1012]
## Describe the bug
If a sync'd project ends up in the "Unsynchronized" state

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Add a new synced project with the option to "Never" sync
2. Wait a bit for the project to end up in the "Unsynchronized" state
3. Buttons (see image) are greyed out.

## Expected behaviour
We should be able to manually sync the project

## Additional context
![image](https://user-images.githubusercontent.com/16961365/119570382-a743e500-bd75-11eb-9a7f-f1f9fc6ae553.png)

**Comment by tom114** [comment]
Completed in #1021
