### ISSUE TITLE
Disable built-in SISTR version from IRIDA

### ISSUE THREAD

**Issue by tom114** [phac-nml/irida#1022]
## Describe your idea for a new feature
SISTR has been built into a plugin pipeline available at https://github.com/phac-nml/irida-plugin-sistr.  This allows the SISTR developers to update SISTR independent of the IRIDA release schedule.  Now that it's available in a plugin we can disable the existing built-in IRIDA pipeline from the main project.

## Describe how you would access this feature?
Removing SISTR as a launchable plugin from the cart.

## Additional information
We may need to keep the old SISTR workflows in the system so that previous analysis results properly display their results, but it should not be launchable from the cart.

**Comment by apetkau** [comment]
Completed in #1270
