### ISSUE TITLE
Managers on synchronized projects cannot add new members to a project

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#1043]
## Describe the bug

If you are a **Manager** on a synchronized project (and not a system **Admin** user) then you cannot add new members to that project (that is, the **Add Project Member** button is missing).

![image](https://user-images.githubusercontent.com/200517/123161684-56d3ac00-d435-11eb-8a6d-3507e4f53f52.png)

However, for non-synchronized projects (i.e., normal projects) you can add new members (the **Add Project Member** button is present).

![image](https://user-images.githubusercontent.com/200517/123161845-8aaed180-d435-11eb-9dfd-0e350a23dd67.png)

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Create a new synchronized project. Add a user `user` as a **Manager** of this project.
2. Login as `user` and go to **Settings > Members** in the project.
3. The **Add Project Member** button will be missing.

## Expected behaviour
I expected to be able to add project members as a **Manager** of a synchronized project.

## Additional context
None.

**Comment by tom114** [comment]
Fixed in #1045
