### ISSUE TITLE
Create administrator console

### ISSUE THREAD

**Issue by tom114** [phac-nml/irida#105]
We should have an administrator console where you can control some configuration options.  This could possibly be designed similar to the project/settings page.  Example config options could include:

* Disable workflow/ncbi submission (useful before an upgrade)
* Set number of allowed active workflows
* Clients, announcements, ncbi uploads
* Display some usage statistics

Many of these options are currently read from the `/etc/irida/irida.conf` file but might be useful to be able to change on the fly.

Imported from GitLab issue #506.  Originally posted on 2017/07/18 10:19AM

**Comment by tom114** [comment]
Possible co-op project?

Imported from GitLab.  Originally posted on 2018/02/08 11:09AM

**Comment by tom114** [comment]
Usage statistics example:
* Number of projects created in last [Time Period]
* Number of samples created in last [Time Period]
* Number of users logged in last [Time Period]

**Comment by joshsadam** [comment]
* I would like to see the creating announcements brought into this system.  This would also require a re-working of the IRIDA announcement system (I have thoughts on this too).
* Gross user management (enabling/deleting/disabling accounts, last used, etc...)

**Comment by tom114** [comment]
Agreed on the user management.  I'd say pretty much everything under the settings cog `⚙` could be moved into an admin console.  Users, groups, remote APIs, clients, announcements.

Re: announcements, I agree it's time to look at a different presentation for them.  I think @joshsadam is creating a new related issue for that.

**Comment by deepsidhu85** [comment]
Usage statistics example addition:

- Number of analyses in last [Time Period]

Different color menu bar for admin panel depending on if user is an admin or not

**Comment by tom114** [comment]
Completed in #794.  Usage statistics will come in a later version.

**Comment by tom114** [comment]
Added a new issue for the usage statics in #799.  Closing this larger issue in favour of that one.
