### ISSUE TITLE
Deal with Galaxy zipped HTML

### ISSUE THREAD

**Issue by pvanheus** [phac-nml/irida#1057]
## Describe your idea for a new feature
When a Galaxy tool outputs HTML it is downloaded from Galaxy as a Zipped HTML. If IRIDA tries to display this (if the dataset is named something .html) it gets displayed as binary data.

One workaround at present is to change the datatype on the Galaxy workflow side (to something like txt) so that it gets downloaded as a text file.

Ideally IRIDA would be able to pick up the "zipped HTML", unpack the HTML from the zip and display that.

## Describe how you would access this feature?
This would be interact with the HTML viewer (https://github.com/phac-nml/irida/pull/849/files#) and the [AnalysisController](https://github.com/phac-nml/irida/blob/development/src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisController.java).

## Additional information
A known limitation is that the current IRIDA HTML viewer expects a single web page. If all the assets of a web page are loaded into this HTML it can get large and unwieldy.

**Comment by apetkau** [comment]
Thanks for writing this up @pvanheus 👍
