### ISSUE TITLE
error starting irida web application for the first time

### ISSUE THREAD

**Issue by Aworwui** [phac-nml/irida#1062]
Hi All,
I kindly need some help to resolve this error with my installation of irida web application 
below is the error message when I try to start tomcat service
[localhost.2021-07-27.log](https://github.com/phac-nml/irida/files/6888027/localhost.2021-07-27.log)
Hope the attach file give you some idea of the error

regards
Archie

**Comment by tom114** [comment]
Hi @Aworwui , I can see the following errors in the log you posted:
```
... Cannot continue startup; base directory [/tmp/irida/reference-files] does not exist!
```
The directories storing IRIDA's data must be created before the server can be started.  Information about configuring those directories can be found in our docs at <https://phac-nml.github.io/irida-documentation/administrator/web/#core-configuration>.  The default locations for these directories is set at https://github.com/phac-nml/irida/blob/development/src/main/resources/ca/corefacility/bioinformatics/irida/config/filesystem.properties:
```
sequence.file.base.directory=/tmp/irida/sequence-files
reference.file.base.directory=/tmp/irida/reference-files
output.file.base.directory=/tmp/irida/output-files
assembly.file.base.directory=/tmp/irida/assembly-files
```

**Comment by ericenns** [comment]
Closed due to inactivity
