### ISSUE TITLE
Order statistics charts by date/time instead of string

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#1066]
## Describe the bug
It looks like the order of some of the columns in the statistics charts are by the string label. For charts that show information related to the date/time it would be nice if the labels were ordered by date/time instead.

![image](https://user-images.githubusercontent.com/200517/127678166-fa476dfe-9656-4576-b72f-bbf356e00684.png)

For example, here you can see that the column for July 2020 and 2021 (`07/20`, `07/21`) are next to each other, instead of grouped by the year.

## Steps to reproduce the problem
1. Open up the **Admin** panel in IRIDA
2. Look at some of the charts (e.g,. Analyses)

## Expected behaviour
I expected the order of the labels to be by date/time.

## Additional context
None.

**Comment by apetkau** [comment]
Note if you encode the date as `YYYY/MM` then ordering by string should be the same as ordering by calendar date (though then you can't change the labels for dates later on to e.g, `July 2021` and so on).

**Comment by ksierks** [comment]
Fixed in  #1221.
