### ISSUE TITLE
Galaxy Integration (0.18.x)

### ISSUE THREAD

**Issue by dfornika** [phac-nml/irida#11]
Which galaxy docker image should be used for integration testing with IRIDA 0.18.x?

Could we get an updated version of this page:

https://irida.corefacility.ca/documentation/developer/setup/galaxy/

That explains how to set up a galaxy docker instance that is configured to work with IRIDA?

**Comment by apetkau** [comment]
It should be the same as for the previous version as nothing has changed since then.  That is `galaxy-irida-17.01:0.17.0-it` (https://hub.docker.com/r/phacnml/galaxy-irida-17.01/).

We will make sure to update that page and provide better integration testing instructions for our next release.

**Comment by dfornika** [comment]
I just found this page:

https://irida.corefacility.ca/documentation/administrator/galaxy/

which has the info that I need for setting up a galaxy docker instance.
