### ISSUE TITLE
Update reach-router to react -router

### ISSUE THREAD

**Issue by joshsadam** [phac-nml/irida#1108]
## What needs changed?

Update pages using `reach-router` to `react-router` v6.  Why?  They are sibling projects, very similar API, but future development will be on `react-router`, since there are only a few pages to update, this should be done now.

## How does it work now?

`reach-router` works now, this is a future preparedness update

## How should it work?

How do you think this component should work?

## Additional information

**Comment by ericenns** [comment]
Fixed in 22.01
