### ISSUE TITLE
Add method to permanently delete (purge) sequence reads from the filesystem

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#1125]
## Describe your idea for a new feature
Currently in IRIDA there's a method to delete sequence reads (or delete samples from a project). But these don't actually remove the sequence read data from the filesystem. Instead, they hide the sequence read data from appearing in a project/unlink it from a sample.

![image](https://user-images.githubusercontent.com/200517/140355995-8471bbe6-24d0-48fc-8b76-87c33f575880.png)

It would be very useful in some cases to be able to permanently delete sequence reads from the filesystem. Perhaps as a separate operation named something like "Purge" (or "Permanently Delete").

## Describe how you would access this feature?
This could possibly appear as a separate operation available to regular users. Or it could appear as an option available only to administrators (who could maybe have a separate view of all "Deleted/unlinked" data and the ability to permanently delete this data).

## Additional information
None.

**Comment by apetkau** [comment]
An updated screenshot of where deleting sequence files is located now:

![image](https://user-images.githubusercontent.com/200517/216126696-6eaf35a0-a4ad-442e-bf5d-7e823f34d3c9.png)

**Comment by ksierks** [comment]
![image](https://user-images.githubusercontent.com/325703/216365156-04d07fa2-5696-4cde-88da-200e6d7f918a.png)

From doing a quick test, I believe if you remove a sample from a project or remove a sequencing run, it deletes those records from the database. In both cases, they leave behind their sequencing object and files. We need a way to clean up sequencing objects.

**Comment by ksierks** [comment]
- deleting a sequence run deletes all the database records (sequencing_run, sequencing_object, sequence_file, samples, etc), but not the actual file on the file system
- deleting a sample with sequence data, deletes the sample from the database, but not the sequencing_object
