### ISSUE TITLE
Unable to manually save results of an analysis back to a sample

### ISSUE THREAD

**Issue by deepsidhu85** [phac-nml/irida#1200]
## Describe the bug
After a SISTR analysis completed and I tried to save the results back to the sample an error was thrown

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Ran SISTR analysis
2. Tried to save results back to sample
3. Error notification was displayed

## Expected behaviour
Expected the results to be saved back to the sample

## Additional context
A solution which has been tested and works is below:

Add the following line to either (`application.properties`,  `application-prod.properties` or `irida.conf` file if using the prod profile)

`spring.jpa.open-in-view=false`

https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#data.sql.jpa-and-spring-data.open-entity-manager-in-view

After adding this the expected behaviour occurs.

**Comment by ericenns** [comment]
Fixed in #1202
