### ISSUE TITLE
Completed colour for status of NCBI Export

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#1312]
## Describe the bug

I have noticed that the final status of an NCBI Export `PROCESSED_OK` is gray. However, I believe an intermediate state is coloured green (I think it's `UPLOADED` but I don't have an example visible now).

I am wondering if the `PROCESSED_OK` state could be switched to be the one that is coloured green, since it is the final state when everything is completely sent to NCBI? I wasn't sure if this is a bug or feature request.

![image](https://user-images.githubusercontent.com/200517/172925708-003efd6a-9e67-464d-b367-b1c11a0edce5.png)

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Export data to NCBI
2. The `PROCESSED_OK` state (final state) is gray.

## Expected behaviour
I expected `PROCESSED_OK` to be green to indicate it's completed successfully.

## Additional context
None

**Comment by joshsadam** [comment]
Do these colors work better for you (if you need to see the actual color they are the default [Tag colors in Ant Design](https://ant.design/components/tag/))  
 

```typescript
const states: ExportTagStates = {
  [ExportUploadState.NEW]: {
    color: TagColor.LIME,
    text: i18n("ExportUploadState.NEW"),
  },
  [ExportUploadState.UPLOADING]: {
    color: TagColor.LIME,
    text: i18n("ExportUploadState.UPLOADING"),
  },
  [ExportUploadState.UPLOADED]: {
    color: TagColor.LIME,
    text: i18n("ExportUploadState.UPLOADED"),
  },
  [ExportUploadState.UPLOADED_ERROR]: {
    color: TagColor.RED,
    text: i18n("ExportUploadState.UPLOAD_ERROR"),
  },
  [ExportUploadState.CREATED]: {
    color: TagColor.BLUE,
    text: i18n("ExportUploadState.created"),
  },
  [ExportUploadState.FAILED]: {
    color: TagColor.RED,
    text: i18n("ExportUploadState.failed"),
  },
  [ExportUploadState.QUEUED]: {
    color: TagColor.BLUE,
    text: i18n("ExportUploadState.queued"),
  },
  [ExportUploadState.PROCESSING]: {
    color: TagColor.BLUE,
    text: i18n("ExportUploadState.processing"),
  },
  [ExportUploadState.PROCESSED_OK]: {
    color: TagColor.GREEN,
    text: i18n("ExportUploadState.processed-ok"),
  },
  [ExportUploadState.PROCESSED_ERROR]: {
    color: TagColor.RED,
    text: i18n("ExportUploadState.processed-error"),
  },
  [ExportUploadState.WAITING]: {
    color: TagColor.CYAN,
    text: i18n("ExportUploadState.waiting"),
  },
  [ExportUploadState.SUBMITTED]: {
    color: TagColor.BLUE,
    text: i18n("ExportUploadState.submitted"),
  },
  [ExportUploadState.DELETED]: {
    color: TagColor.VOLCANO,
    text: "DELETED",
  },
  [ExportUploadState.RETIRED]: {
    color: TagColor.GOLD,
    text: "RETIRED",
  },
  [ExportUploadState.UNKNOWN]: {
    color: TagColor.ORANGE,
    text: "UNKNOWN",
  },
};
```

**Comment by apetkau** [comment]
@joshsadam thanks so much for looking at this.

I think those colours are great. But I'm wondering if the `LIME` and `GREEN` colours are too close and we should use different colours for `NEW`, `UPLOADING`, and `UPLOADED`?

It seems that we're using **blue** colours for processing, but then there is **cyan** for waiting.

Would this make sense:
* The `NEW` state should be **gray** since nothing has happened to it yet.
* States that are waiting for the next action should be **cyan**: `UPLOADED`, `CREATED`, `QUEUED`, `WAITING`, `SUBMITTED`
* States that are more related to some action currently happening should be **blue**: `UPLOADING`, `PROCESSING`
* The `PROCESSED_OK` state (final state) should be **green**
* Other error states are good as they are (different colours like **red**, **orange**, etc)

Does that make sense? Is there another way to divide up the states and assign colours you had in mind?

**Comment by joshsadam** [comment]
That sounds good. I will update it. Thanks @apetkau

**Comment by joshsadam** [comment]
@apetkau can you take a final look at this file and make sure it is updated properly.

https://github.com/phac-nml/irida/pull/1311/files#diff-25ef9c16f92c1b52d64eef9bf812dcc41da3e47a0fd4fcb1bbc9020d01df9103
