### ISSUE TITLE
Display sequence file coverage on the Sample details (or possible the Project > samples) page.

### ISSUE THREAD

**Issue by joshsadam** [phac-nml/irida#133]
As per my discussion with Ashley K. @thomas.matthews

Imported from GitLab issue #597.  Originally posted on 2018/01/26 01:41PM

**Comment by apetkau** [comment]
In addition to sequence file coverage, it would be nice to display the **number of bases** (output of fastqc) in the sample details and the **Project > samples** page.

**Comment by apetkau** [comment]
Fixed in https://github.com/phac-nml/irida/pull/1360
