### ISSUE TITLE
Samples in associated projects are not being loaded

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#1340]
## Describe the bug

If you create a container project to contain many **Associated Projects** the samples in those associated projects are not available.

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Create a new project **NewProject1** and add a sample.
2. Create another project **ContainerProject** and set **NewProject1** as an associated project.
3. No samples will display in **ContainerProject**.

## Expected behaviour

I expected samples in **NewProject1** to also display in **ContainerProject**.

### 1. Empty `ContainerProject`
![image](https://user-images.githubusercontent.com/200517/178600900-8d21e824-7b6d-4388-bc95-98ecd9202cfe.png)

### 2. `ContainerProject` has `NewProject1` associated with it

![image](https://user-images.githubusercontent.com/200517/178601044-26228573-e2b2-4088-b024-76bb840b527c.png)

### 3. `NewProject1` has a sample

![image](https://user-images.githubusercontent.com/200517/178601115-eee1dc3d-05fb-4077-b9cb-1939f56ce24f.png)

**Comment by ericenns** [comment]
Hi @apetkau I am unable to reproduce. Did you follow the instructions here on how to display samples from an associated project. https://phac-nml.github.io/irida-documentation/user/user/samples/#projects-filtering

**Comment by apetkau** [comment]
Thanks @ericenns , yes you're right. That does work. I can see associated project samples now.

I did not realize that this was how you enabled associated samples/projects. I'm wondering if there's a way to make this clearer? Like maybe having it in the **Sample Tools** drop-down. Or a visible toggle like **Show all associated projects** next to **Filter by File** or something?
