### ISSUE TITLE
Add project identifier to all drop-downs where the project name is displayed

### ISSUE THREAD

**Issue by joshsadam** [phac-nml/irida#1347]
## What needs to be changed?
Add project identifier to all drop-downs where the project name is displayed

## How does it work now?
Currently, only the project name is displayed in the drop-down when selecting a project. 

## How should it work?
The project identifier should be displayed beside the name.  

## Additional information
![image](https://user-images.githubusercontent.com/11295750/183104800-56e5a477-74ba-478c-8a24-eaccd774f76d.png)

**Comment by ericenns** [comment]
Completed in #1352
