### ISSUE TITLE
Unify sample validation/existence endpoints

### ISSUE THREAD

**Issue by ericenns** [phac-nml/irida#1349]
## What needs changed?
Replace all existing Sample existence checks with a single endpoint that can be used for validating Sample Name when creating a new Sample, checking for Sample existence when sharing/moving samples, and for validating Sample names when Filtering Samples.

## How does it work now?
Currently there are 4 endpoints within 2 Ajax controllers that perform similar operations that we want to unify into a single endpoint. These are the following:
* `validateNewSampleName` in `ProjectSamplesAjaxController.java`
  * This is used to validate the name of Sample attempting to be created
* `getSampleIdsForProject` in `ProjectSamplesAjaxController.java`
  * This is used to validate Samples attempting to be shared/moved to another Project
* `getSampleNamesForProject` in `ProjectSamplesAjaxController.java`
  * This is used to validate Samples attempting to be shared/moved to another Project
* `checkSampleNames` in `SamplesAjaxController.java`
  * This is used to validate Sample names when Filtering by File on Project Samples page

## How should it work?
There should be a new endpoint in `ProjectSamplesAjaxController.java` with a Post Mapping `/validate` which takes a Request Body that looks like the following:

```
{
    samples: [
        { name: "SAMPLE_NAME" },
        ...
    ],
    associated_project_ids: [ASSOCIATED_PROJECT_ID,...] //optional
}
```

and produces a Response Body that looks like the following:

```
{
    samples: [
        { 
            id: SAMPLE_ID, // id will be NULL if the sample does exist in the Project or the Associated Projects
            name: "SAMPLE_NAME"
        },
        ...
    ] // There must be a entry for each Sample in the Request Body
}
```

## Additional information
Add any other context, files, or screenshots about this request here.

### Scenario 1: Validating Sample Name when creating a new Sample

PROJECT_ID = The Project that the user is attempting to create a Sample in

#### Sample Name does not exist in the current Project
```
POST /ajax/projects/PROJECT_ID/samples/validate
BODY
{ 
    samples: [
        {name: "NEW SAMPLE"}
    ]
}

RESPONSE
{
    samples: [
        {id: NULL, name: "NEW SAMPLE"},
    ]
}
```

#### Sample Name exists in the current Project
```
POST /ajax/projects/PROJECT_ID/samples/validate
BODY
{
    samples: [
        {name: "EXISTING SAMPLE"},
    ]
}

RESPONSE
{
    samples: [
	    {id: 1, name: "EXISTING SAMPLE"},
    ]
}
```

### Scenario 2: Validating Samples when Sharing/Moving

PROJECT_ID = The source project
TARGET_PROJECT_ID = The destination project

#### Sample does not exist in Target Project
```
POST /ajax/projects/TARGET_PROJECT_ID/samples/validate
BODY
{
    samples: [
        {name: "SAMPLE 2"}
    ]
}

RESPONSE
{
    samples: [
        {id: NULL, name: "SAMPLE 2"},
    ]
}
```

#### Sample exists in Target Project
```
POST /ajax/projects/TARGET_PROJECT_ID/samples/validate
BODY
{
    samples: [
        {name: "SAMPLE 1"} // id: 1
    ]
}

RESPONSE
{
    samples: [
        {id: 1, name: "SAMPLE 1"},
    ]
}
```

#### Another Sample with the same Sample Name exists in Target Project
```
POST /ajax/projects/TARGET_PROJECT_ID/samples/validate
BODY
{
    samples: [
        {name: "SAMPLE 2"} // id: 2
    ]
}

RESPONSE
{
    samples: [
        {id: 3, name: "SAMPLE 2"},
    ]
}
```

## Scenario 3: Validating Sample Names during Filter by File

PROJECT_ID = The Project that the user is currently viewing Samples from
ASSOCIATED_PROJECT_ID = The Project that is associated with the current Project

### When the user is filtering Samples that exist in the Project
```
POST /ajax/projects/PROJECT_ID/samples/validate
BODY
{
    samples: [
        {name: "SAMPLE 1"},
        {name: "SAMPLE 2"}
    ]
}

RESPONSE
{
    samples: [
        {id: 1, name: "SAMPLE 2"},
        {id: 2, name: "SAMPLE 2"},
    ]
}
```

### When the user is filtering Samples that do not exist in the Project
```
POST /ajax/projects/PROJECT_ID/samples/validate
BODY
{
    samples: [
        {name: "SAMPLE 1"},
        {name: "SAMPLE 2"}
    ]
}

RESPONSE
{
    samples: [
        {id: NULL, name: "SAMPLE 2"},
        {id: NULL, name: "SAMPLE 2"},
    ]
}
```

### When the user is filtering Samples that do not exist in the Project but exist in an Associated Project which is not currently filtered/visible
```
POST /ajax/projects/PROJECT_ID/samples/validate
BODY
{
    samples: [
        {name: "SAMPLE 3"},
        {name: "SAMPLE 4"}
    ]
}

RESPONSE
{
    samples: [
        {id: NULL, name: "SAMPLE 2"},
        {id: NULL, name: "SAMPLE 2"},
    ]
}
```

### When the user is filtering Samples that do not exist in the Project but exist in an Associated Project which is currently filtered/visible
```
POST /ajax/projects/PROJECT_ID/samples/validate
BODY
{
    samples: [
        {name: "SAMPLE 3"},
        {name: "SAMPLE 4"}
    ],
    associated_project_ids: [ASSOCIATED_PROJECT_ID]
}

RESPONSE
{
    samples: [
        {id: 3, name: "SAMPLE 2"},
        {id: 4, name: "SAMPLE 2"},
    ]
}
```

**Comment by ericenns** [comment]
On further consideration, `validateNewSampleName` will remain unchanged as it also checks the format of the sample name which is not necessary for the other endpoints.

**Comment by ksierks** [comment]
For the scenario, that a sample exists in both the project and associated project with the same name, what should be returned? A list of sample ids?

**Comment by ericenns** [comment]
> For the scenario, that a sample exists in both the project and associated project with the same name, what should be returned? A list of sample ids?

This would only be encountered when validating sample names when filtering the project samples table by file, right?

If so then just the id of the first sample found would be ok. @deepsidhu85 any thoughts?

**Comment by deepsidhu85** [comment]
> ASSOCIATED_PROJECT_ID = The Project that is associated with the current Project

@ericenns @ksierks In this scenario yeah it should be perfectly fine to just return the id of the first sample that is found

**Comment by ksierks** [comment]
@ericenns @deepsidhu85 I hope it's okay, but I did return the list of of found sample ids. I was able to create a new query and it simplified the service layer logic. I'm also just a little worried I'm going to look back at my own work in the future and wonder why I didn't send back a complete list, lol.

**Comment by ericenns** [comment]
Completed in #1353
