### ISSUE TITLE
Develop AMR detection tool

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#137]
Imported from GitLab issue #605.  Originally posted on 2018/02/08 10:00AM

**Comment by apetkau** [comment]
No. This is not integrated into IRIDA.

Imported from GitLab.  Originally posted on 2018/11/13 11:16AM

**Comment by tom114** [comment]
@aaron.petkau should we call this complete now?

Imported from GitLab.  Originally posted on 2018/11/13 11:12AM

**Comment by apetkau** [comment]
Added a Galaxy tool for [staramr](https://github.com/phac-nml/staramr) - https://toolshed.g2.bx.psu.edu/view/nml/staramr/fef5aff062c7

Imported from GitLab.  Originally posted on 2018/06/06 02:47PM

**Comment by apetkau** [comment]
Related to #558 #557 but with our own custom code that uses resfinder/pointfinder databases.

Imported from GitLab.  Originally posted on 2018/02/08 10:01AM

**Comment by apetkau** [comment]
Make use of:

* [ ] - staramr
* [ ] - rgi
* [ ] - ariba

**Comment by apetkau** [comment]
This was completed in https://github.com/phac-nml/irida-plugin-amr-detection/pull/1. Any other issues with AMR detection pipeline I will likely move to the plugin repository.
