### ISSUE TITLE
Investigate skesa (NCBI assembler) as possible replacement to SPAdes

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#138]
Imported from GitLab issue #606.  Originally posted on 2018/02/08 10:01AM

**Comment by apetkau** [comment]
This assembler is ultra-fasta (about 1 min/genome).  Binary at ftp://ftp.ncbi.nlm.nih.gov/pub/agarwala/skesa/.  Unsure when code will be released by NCBI.

Imported from GitLab.  Originally posted on 2018/02/08 10:02AM

**Comment by tom114** [comment]
I'd suggest maybe adding this as an *additional* assembler for IRIDA.  No reason we only need 1 assembly pipeline.

**Comment by tom114** [comment]
This will be completed in #234
