### ISSUE TITLE
Add a method to batch-delete analysis pipelines

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#143]
Imported from GitLab issue #613.  Originally posted on 2018/02/16 03:20PM

**Comment by tom114** [comment]
This is the situation that prompted this request:

One of our users enabled automated assembly on a project then uploaded ~200 samples. That created a huge backlog in our queue that our system wasn't able to handle. We wanted a simple way to delete many queued analyses but found that we could only do it one-by-one through the current interface.

Imported from GitLab.  Originally posted on 2018/03/25 11:33AM
Originally posted by Dan Fornika
