### ISSUE TITLE
Don't keep filters/search terms after leaving page/reentering it

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#146]
Sometimes the search/filter terms remain even after you switch pages and back. This is causing confusion for people as they don't realize the filter is still active.

Imported from GitLab issue #619.  Originally posted on 2018/03/21 09:30AM

**Comment by joshsadam** [comment]
I think this is only still on the Project Samples page, will be removed when this page is merged with the Line List Page.  It is a remnant of DataTables.  This is an interesting issue though because we have had people go both directions on it.

**Comment by ericenns** [comment]
Closing as outdated
