### ISSUE TITLE
Link from Analysis "Input Files" to Sample details page

### ISSUE THREAD

**Issue by tom114** [phac-nml/irida#168]
It'd be useful to have a direct link to the Sample associated with the input reads for an analysis rather than just linking to the FastQC results for those reads.

Imported from GitLab issue #656.  Originally posted on 2018/06/18 12:14PM\Posted by Peter Kruczkiewicz

**Comment by joshsadam** [comment]
* List both the sample and the input files used for the analysis.
* Samples may have been deleted, but input files will still exist (need a way to display this).
