### ISSUE TITLE
It's possible to wind up with invalid files after synchronizing

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#175]
It's possible to end up with invalid fastq files after synchronizing, even though the status is still "Synchronized". There's no way for someone currently to know if they files were copied exactly. We should have additional checks (e.g., checksum) done after a sync.

Imported from GitLab issue #668.  Originally posted on 2018/08/08 02:25PM

**Comment by tom114** [comment]
Re-opening as we should add a checksum state.  !1379 only checks file size.

Imported from GitLab.  Originally posted on 2018/08/16 01:09PM

**Comment by tom114** [comment]
Fixed in !1379

Imported from GitLab.  Originally posted on 2018/08/16 01:09PM

**Comment by tom114** [comment]
Wow.  Getting a 200 is super surprising.  We'll have to take a further look into it for something like a checksum.  The existing checksum in the REST API wouldn't work because that's the initial upload checksum so we'll need to add something else.

Imported from GitLab.  Originally posted on 2018/08/08 04:05PM

**Comment by apetkau** [comment]
It looks like the request for getting a file still returns "200 OK", even if the connection is interrupted half-way through, leading to no errors reported about a file transfer.

Imported from GitLab.  Originally posted on 2018/08/08 03:28PM

**Comment by apetkau** [comment]
I can reproduce this scenario by restarting IRIDA in the middle of a sync. The project status will get set to "SYNCHRONIZED", but the fastq files will be truncated. Often this results in errors with fastqc, but not always, which can lead to users believing that files were properly synced.

Imported from GitLab.  Originally posted on 2018/08/08 02:48PM

**Comment by tom114** [comment]
This was fixed with the file size check.  The checksum test was broken into another issue in #242
