### ISSUE TITLE
Make pipeline messages.properties keys consistent

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#176]
Currently, some keys use the pipeline/workflow name converted to lower-case (https://github.com/phac-nml/irida/blob/development/src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java#L228) but other keys use the analysis type (https://github.com/phac-nml/irida/blob/development/src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java#L164).  These should be made consistent.

Imported from GitLab issue #670.  Originally posted on 2018/08/14 01:17PM

**Comment by tom114** [comment]
Closing due to age of issue and ongoing changes to how the workflows are presented in #559
