### ISSUE TITLE
Users unable to delete sequencing data from a sample after release 0.22.0

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#177]
There are reports of users (who are managers on a project) unable to delete sequencing data from a sample after the upgrade to 0.22.x.

Imported from GitLab issue #671.  Originally posted on 2018/08/20 04:52PM

**Comment by apetkau** [comment]
I have tried a bit, but am unable to reproduce this issue. I will keep working at it for a bit.

Imported from GitLab.  Originally posted on 2018/08/21 09:42AM

**Comment by tom114** [comment]
This seems to not be an issue anymore.  It was possibly a caching issue.  Closing.
