### ISSUE TITLE
Improve error reporting in IRIDA when pipeline fails

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#184]
Related to https://github.com/phac-nml/irida/issues/55 and https://github.com/phac-nml/irida/issues/54

Imported from GitLab issue #681.  Originally posted on 2018/10/03 10:29AM

**Comment by apetkau** [comment]
Maybe add message to users in situations where a user may need to resubmit a job in IRIDA (and also let them easily do this #633 )

Imported from GitLab.  Originally posted on 2018/10/03 03:46PM

**Comment by tom114** [comment]
This is being handled by #559
