### ISSUE TITLE
Link to BioPerl-1.6.901 is broken

### ISSUE THREAD

**Issue by dfornika** [phac-nml/irida#2]
The link to BioPerl-1.6.901 on the [galaxy setup documentation](https://irida.corefacility.ca/documentation/developer/setup/galaxy/) is a dead-end.

http://search.cpan.org/CPAN/authors/id/C/CJ/CJFIELDS/BioPerl-1.6.901.tar.gz

There is a newer version available:

http://www.cpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.6.924.tar.gz

...or there is a snapshot of version 1.6.901 available on github:

https://github.com/bioperl/bioperl-live/archive/bioperl-release-1-6-901.tar.gz

**Comment by apetkau** [comment]
Thanks for letting us know.  We've replaced all links in 4145405e2cd42a7e59d04e9020a335589b22861b.
