### ISSUE TITLE
Upload Button does nothing

### ISSUE THREAD

**Issue by happykhan** [phac-nml/irida#230]
The upload button here does nothing.
![screenshot from 2018-12-19 11-01-51](https://user-images.githubusercontent.com/1452696/50216557-010e7c80-037e-11e9-85c1-7abeafc36aef.png)

I click , select file, then nothing happens . 

I can upload a reference through the Project > settings >  reference files. 

I can't see any obvious errors on journalctl or  /var/log/catalina.out

**Comment by happykhan** [comment]
Ah.

Nginx issue, where some (not all) upload/download functions use chunking; which is a  http 1.1. Nginx uses 1.0 by default. Explicitly set 

`               proxy_http_version 1.1;`


in nginx.conf

**Comment by apetkau** [comment]
Thanks for updating the issue with the solution :)
