### ISSUE TITLE
Word wrap - breaking on non-space character

### ISSUE THREAD

**Issue by glwinsor** [phac-nml/irida#24]
Another very simple fix. Would it be possible to break on a space character instead of a non-space character for the 'Project Name" column?

<img width="1119" alt="screen shot 2018-04-03 at 10 14 34 am" src="https://user-images.githubusercontent.com/824607/38264489-fbc2a90e-3727-11e8-9c56-4fb1e09a0bf2.png">

**Comment by joshsadam** [comment]
That does seem like a good idea, thank @glwinsor

**Comment by joshsadam** [comment]
Hi @glwinsor I just pushed to our local copy some css that will clean that up.  Hopefully it will be out in the next release for you.  Thanks for sending feedback, I love it :)
