### ISSUE TITLE
DISCUSSION: Front-end Updates,  State Management and UI Frameworks

### ISSUE THREAD

**Issue by joshsadam** [phac-nml/irida#25]
This is a continuation of a discussion started in #23, in which I stated:

> One way I am considering going is moving towards using [React](https://reactjs.org/) and utilizing the [Ant Design Framework](https://ant.design/).  They have lots of well tested and used components (>26k stars on [GitHub](https://github.com/ant-design/ant-design)), but particularly interesting and applicable to this issue is the [TreeSelect](https://ant.design/components/tree-select/).

This is meant to be an **open discussion** on the path to updating the IRIDA front-end.  I wanted to put this discussion here, as opposed to an email chain, so that it is visible to everyone and everyone can comment.  Please note that things stated here are conceptual and no timelines have been defined.  This is here to keep track of thoughts and to open discussions.

## Background

Early stages of development on the NGS Archive (the precursor to IRIDA) began using a Java based UI framework called [Vaadin](https://vaadin.com/).  We then switched over to the Government of Canada [Web Experience Toolkit (WET)](https://wet-boew.github.io/wet-boew/index-en.html).  The backbone of WET is [jQuery](https://jquery.com/) and [Bootstrap](https://getbootstrap.com/docs/3.3/) which are still found as the foundations of the current iteration of IRIDA. [AngularJS](https://angularjs.org/) was added to facilitate complex UI interactions without the "spaghetti code" that can result from complex UI.

We are currently using quite a bit of 3rd party libraries to meet the application requirements, including input validation, file up-loaders, colour utilities, icon fonts, date utilities, and data tables to name a few.

## Where I would like the platform to head

There are several areas I would like to target the front-end for cleanup and refactoring:

1. Thymeleaf Templates
1. Removal of AngularJS
1. Moving Forward

#### HTML Templates

[Thymeleaf](https://www.thymeleaf.org/) is used as our sever-side HTML templating engine.  Our current templating strategy is can become overly complex, for example for a basic page to get rendered it goes through 3 layers, complicating where things are loaded onto the page:

```
base.html --> page.html --> content page ==> rendered HTML
```

This gets even more complicated for pages that have tabs, eg. Project specific:

```
base.html --> page.html --> page-wrapper --> content page ==> rendered HTML
```

I think restructuring the `base.html` and `page.html` into a single page would be a good start, but more work needs to be done into simplify this templating, possibly moving some to the client.  I also think clear cut rules should be established stipulating when client-side vs server-side templating should be used.

#### JavaScript Templates

Currently all server-side templating is completed on HTML files.  This leaves us in a situation where if we need internationalization, url encoding, or other templating in JavaScript there needs to be a script tag on the HTML page that contains an object of the templated values, and then the external JavaScript needs to reference the object in the global namespace.  This works, but creates tight coupling between the HTML and external scripts.

Thymeleaf has the capability to handle JavaScript templating.  We have previously abstained from using it as we have had issues with the caching of templates.  These issues have mostly been resolved.  I think we should test using Thymeleaf to template JavaScript files under the following conditions:
  * Only internationalization and url encodings should be templated
  * Data sets should be pulled in through an AJAX requests as it has the potential to lead to extremely large files. 

### Removal of AngularJS

AngularJS was added to the project about 5 years ago to help with client side templating and eliminating some the the "spaghetti code" that can happen in large projects.  It was never fully utilized and has lead to a lot of partial implementations and workarounds to get everything to work properly.  There is also an issue where there is a script that is required by the entire application, but does very little, and other pages "hack" into this script (`app.js`) - this was a poor design decision I made.  New AngularJS code has not been added to the code base for some time (except in extending old pages).

#### How to remove

Re-writing all the AngularJS code in the application would be an enormous waste of time.  What I propose is:
  * Remove the `app.js` and only load AngularJS on the pages that currently need it.  The cart and session handler would need to be cleaned up for this.
    * There is an issue with an AngularJS HttpInterceptor that needs to be removed within `app.js` 
  * Only remove AngularJS from specific pages as the code gets updated (no direct push to remove).

### Moving Forward

I have spent the past couple months playing with a lot (really a lot) of different JavaScript libraries trying to come up with a solution that will work best for the IRIDA Line List (Metadata) Page.  This will possibly become the most complex page in the application, as well as hopefully being a great way for our users to gleam insights into their data.  What I have been looking for is:

  * A table interface for displaying and modifying metadata for a samples.
  * State management and UI Frameworks.

#### Table Interface

I would like to propose that the new standard for tables in the IRIDA Application is [ag-grid](https://www.ag-grid.com/documentation-main/documentation.php).  It is a commercial table, but has a free version that meets the current needs of IRIDA. @peter.kruczkiewicz has already incorporated ag-grid into the soon to be released analysis output preview.  

  * [DataTables](https://datatables.net/) are used on a number of pages (I just updated a bunch of them to remove dandelion), but DataTables do not meet all of the new requirements, and behave and look slightly different than ag-grid.  
  * As with the AngularJS proposal, I submit that these should only be updated as the respective pages get updated.

#### State Management and UI Framework

During my research to find a really good table, I have played with many UI frameworks including [Vue](https://vuejs.org/), [React](http://reactjs.org) and even the latest release and [Angular](https://angular.io/). Vue and React appear to be good candidates for a UI Framework for IRIDA as they primary focus on the **view** and not a complete **MVC pattern**.

Both UI frameworks have the capability of working with their own state management, [Veux](https://github.com/vuejs/vuex) for Vue and [Redux](redux.js.org) fro React.  I have a working example of React, Redux, and ag-grid working together and it seems to be a great fit.

As I stated in the GitHub issue, I have been playing with the [Ant Design System](https://ant.design/).  It is a very popular React UI Framework that has [>26K GitHub stars](https://github.com/ant-design/ant-design) and appears to be updated on a daily basis. It has a component that appears to fit IRIDA needs and appearance wise is not too dissimilar from bootstrap that it would appear out of place.  ~~There is also a [good Vuejs version](https://www.iviewui.com/) if the team decides they would like to use Vue.~~ (Removed because ag-grid has awesome support for React but not Vue).

## Open for lots of discussion

I wanted to open this discussion as these are the thoughts that keep me awake at night, and I would really appreciate the teams feedback so we can move forward on this together.

@peterk87 @tom114 @apetkau @dfornika 

Please tag anyone who needs to be involved in this discussion.

**Comment by dfornika** [comment]
I'm excited to hear that there are plans to integrate some newer front-end libraries like React. One thing that I'm concerned about is that we'll be mixing multiple technologies and I'm not sure how well they will co-exist. In particular, AngularJS and React/Redux each have their own ways of storing state (AngularJS 'scopes' vs. the Redux 'store'). If they're both present on the same page, we'll need to keep them in sync in some way. Is there an existing well-designed solution for that? Can we do it ourselves in a disciplined way?

**Comment by joshsadam** [comment]
Off the top of my head, the only global state that is maintained between pages is the cart, this is something that needs addressing sooner rather than later anyways.

**Cart Issues**

1. We had a coop student integrate pulling data from IRIDA into Galaxy.  When he did this, he tightly coupled the Galaxy scripts with the Cart scripts.  These need to be separated into two files.
2. The cart has a major UX issue.  If you tab through the UI, the cart will open and and does not close if you hit the close button (you need to click the cart button in the navbar which properly opens the side panel and then click close - really bad 🤬).  @tom114 and I have spoken about different ways of updating the UI, including removing that off-canvas section, and having a complete page for displaying and manipulating the cart.  *This is a whole other issue that needs to be discussed further*.

All that said, I think if we took the approach of only updating pages that need to be updated, and replace the angularjs components with either vanilla javascript or React components, I do not think we will run into any major issues (unless I am missing something).  The cart does not *need to* fall into the state initially, this can occur later.  Since the cart currently updates its state from server calls and native js events (except for removing which would be simple to update).

Using redux, it is possible to get access to the "store" and get the current state and update the state from anywhere (outside of React) that can get a handle on it. (Dan Abramov, redux's creator, has an excellent free video series on redux on [Egghead](https://egghead.io/courses/getting-started-with-redux)).

@dfornika are there other instances where we would need communication between React/redux and angularjs that you can think of?

**Comment by dfornika** [comment]
I think that may reveal one more architectural conflict between our current architecture and the approach that's taken with most React/Redux apps. As I understand it, React/Redux is mostly used in 'single-page apps', where there isn't much (or any) navigating and re-loading between pages.

If we introduce Redux, will we be able to create a single global store, or will there be a separate store for each page?

**Comment by joshsadam** [comment]
I think the introduction of redux would need to be on a page per page basis.  I think what we are going to be seeing individual pages within IRIDA turning into their own SPA's.  The line list page that I am currently working on definitely applies to this, as well as pages like pipeline launch page, and analysis details pages.
