### ISSUE TITLE
Slow loading analysis/all action

### ISSUE THREAD

**Issue by glwinsor** [phac-nml/irida#259]
Hi guys,

When I try to view a list of all analyses that have been run on our SFU instance, it takes a very long time to load. I get a "Processing" message and it hangs for around 10 seconds sometimes. 

I wanted to establish whether it would be realistic to expect it to take this long for about 1200 analyses to be listed. I'm assuming that all results are being pulled out at once and the front end framework is handling the pagination.

I suspect this is a resource allocation issue for our application server but having some more insight from you guys before approaching the university team would be helpful.

Thanks

**Comment by apetkau** [comment]
Is this just when viewing 10 per page or more?  We have tens of thousands of analyses and it takes me maybe 1-2 seconds to load the page. But, when viewing 100 per page it can take 10+ seconds to switch pages.

Pagination is handled server-side.

We also have 8 GB of memory and 8 cores allocated to our main IRIDA server. Do you have less resources allocated?

**Comment by glwinsor** [comment]
This is for loading just 10 per page.  I don't have the specs for our application server but I don't suspect you need much for a simple query like this. Perhaps it's a database issue. I'll follow up once I know more.
