### ISSUE TITLE
Javascript libraries sometimes get cached between builds

### ISSUE THREAD

**Issue by tom114** [phac-nml/irida#304]
## Describe the bug
When switching between branches of IRIDA where some JS libraries were updated, it seemed that one of the front end dependency managers weren't properly getting the right version of a JS library to use.  If tested with a fresh checked out repo, the problem doesn't show up.

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Be on branch X where there's a JS library change
2. Switch to branch Y without the JS change
3. Run the web server with Jetty.  You *may* have issues with the changed JS library.

## Expected behaviour
Properly download and serve the correct versions of the library.  Other option would be to add something to the `mvn clean` which blows away the cached JS files from the webapps directory.

## Additional context
We ran into this while testing #263 switching between that branch, `master`, and `development`.

**Comment by joshsadam** [comment]
Fixed in #543 which adds a cache buster to the end of resource paths to prevent this from happening.
