### ISSUE TITLE
Cannot add samples into cart when from associated Projects

### ISSUE THREAD

**Issue by Takadonet** [phac-nml/irida#331]
## Describe the bug
Issue is I am not able to add samples from certain associated projects into the cart.

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Navigate to project with associated projects linked
2. Select one or more associated projects under **Associated Projects** dropdown
3. Click **Select All** 
4. Click **Add To Cart**

## Expected behaviour
Expect to see samples added to the cart or error messaging indicate why they were not.

**Comment by joshsadam** [comment]
@Takadonet I cannot reproduce this error.  Can you give me more specific information?

**Comment by Takadonet** [comment]
Issued been resolved in previous releases!
