### ISSUE TITLE
Can group members view details from other groups?

### ISSUE THREAD

**Issue by glwinsor** [phac-nml/irida#35]
I just created 3 mock users for a 'Reviewers' group and assigned them all as "group members". 

While not having tested too much with groups yet, we did have one existing group on the server called "MyGroup" for which only "Gemma Hoad" is the only member and group owner.

One of the mock users that I am logged in as (confirmed as group member) is able to see both the Reviewers and MyGroup groups. If the mock user clicks on MyGroup -> Gemma Hoad, he is able to view her user details and all of her projects (but is denied access to any of the project details). 

I was wondering if this is expected behaviour, or perhaps a configuration error on my end where I opened access by mistake, or if is it a bug.

Thanks,
Geoff

**Comment by tom114** [comment]
Hey @glwinsor, the user page project listing is going away in the next release.  Only admins will be able to see that list.

As for other users being able to view the members in a group, this is something that could be discussed.  When we first built the user group features we didn't want to hide which users were in a group.  In fact we thought it would be important to see which users were in a group so if they added the group to a project they knew who they were adding.  Happy to discuss other options with that if you guys feel it's a concern.

Tom

**Comment by glwinsor** [comment]
Hi Tom,

I see what you mean and it makes sense to allow members of a group to view all members. It also sounds like you guys are considering letting a user view members of a group that he/she doesn’t belong to yet, or would like to share a project with. I guess that is OK too considering the reasons you give.  If that’s the case, I think we’re OK with that but you might want to let users control how much of their personal info (e.g. phone number or email) is displayed.

Cheers,
Geoff




On May 2, 2018, at 10:06 AM, Tom Matthews <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @glwinsor<https://github.com/glwinsor>, the user page project listing is going away in the next release. Only admins will be able to see that list.

As for other users being able to view the members in a group, this is something that could be discussed. When we first built the user group features we didn't want to hide which users were in a group. In fact we thought it would be important to see which users were in a group so if they added the group to a project they knew who they were adding. Happy to discuss other options with that if you guys feel it's a concern.

Tom
