### ISSUE TITLE
Update mechanism to get status of workflows from Galaxy

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#351]
## Describe your idea for a new feature

Currently, we make use of an old API method in Galaxy which runs workflows and does not return until all jobs in Galaxy are scheduled. This method in the Galaxy API is deprecated in favour of a method which returns right away before all jobs are scheduled (`run` vs. `invoke` - https://bioblend.readthedocs.io/en/latest/api_docs/galaxy/all.html#bioblend.galaxy.workflows.WorkflowClient.run_workflow).  Updating to use `invoke` will require changes to how we check for the status of running workflows in IRIDA.

## Describe how you would access this feature?

This would involve updating the [blend4j](https://github.com/galaxyproject/blend4j) project, and then updating the IRIDA/Galaxy interaction code. This would particularly impact the IRIDA pipeline status display:

![image](https://user-images.githubusercontent.com/200517/56164990-79392780-5f97-11e9-8c1f-971850071db9.png)

## Additional information

Related to issue #328

**Comment by tom114** [comment]
Related to #693
