### ISSUE TITLE
Attach sources to installed IRIDA packages for IRIDA plugins

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#368]
## Describe your idea for a new feature

Attach sources to installed IRIDA packages for IRIDA plugins.

## Describe how you would access this feature?
1. User would run `mvn install -DskipTests` to install IRIDA to local Maven repository.
2. This would include the sources, which could then be displayed in Eclipse and used to help develop IRIDA Plugins (https://github.com/phac-nml/irida-plugin-amr-detection).

## Additional information

Without sources attached I get this message in Eclipse:

![image](https://user-images.githubusercontent.com/200517/56822011-73540980-6815-11e9-9f40-574bd4a2381c.png)

**Comment by ericenns** [comment]
Closing as this was added in gradle build conversion.
