### ISSUE TITLE
Bad gateway when trying to reach https://irida.corefacility.ca/galaxy-shed/

### ISSUE THREAD

**Issue by PHemarajata** [phac-nml/irida#37]
Hi! I was trying to install SNVPhyl from IRIDA toolshed into my local Galaxy server and ran into a bad gateway error. If you could check it out, I'd really appreciate it! I love this tool! Thank you.

**Comment by apetkau** [comment]
Thanks for letting us know.  This should be fixed now.  Please let us know if you have any more trouble.
