### ISSUE TITLE
Error while running smalt_map

### ISSUE THREAD

**Issue by PHemarajata** [phac-nml/irida#39]
Hi, so sorry again for posting another issue. I finally installed all dependencies and started a paired read workflow. Everything was halted at smalt_map with the following message:

### An error occured while running the tool irida.corefacility.ca/galaxy-shed/repos/nml/smalt_map/smalt_map/1.1.0.

Tool execution generated the following messages:
Fatal error: You cannot do that!! What were you thinking!
Command line:  smalt map -o /Users/peerahemarajata/galaxy/database/files/000/dataset_86.dat -f bam -n 1 -l pe -i 1000 -j 20 -r 1 -y 0.5 temp /Users/peerahemarajata/galaxy/database/files/000/dataset_3.dat /Users/peerahemarajata/galaxy/database/files/000/dataset_4.dat
Opening read files ...
Reading reference sequences ...
Reading hash table ...
=-=-=-=-= Hash Index Stats =-=-=-=-=
Hash index with collisions.
Word length:              13 bases
Skip step:                6 bases
Number of hash keys:      262144
Number of word positions: 459177
Number of different words:        445960
Maximum number of words per key:  10
Number of keys without words:     47875
=-=-= End of Hash Index Stats =-=-=
Processing query reads ...
[0] smalt.c:1386 ERROR: assertion failed 
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
/Users/peerahemarajata/shed_tools/irida.corefacility.ca/galaxy-shed/repos/nml/smalt_map/62faa1906fd7/smalt_map/smalt_map.sh: line 52:  1688 Segmentation fault: 11  samtools sort -@ $GALAXY_SLOTS $smaltout 'temp2'
mv: /Users/peerahemarajata/shed_tools/irida.corefacility.ca/galaxy-shed/repos/nml/smalt_map/62faa1906fd7/smalt_map/smalt_map.sh: line 52:  1691 Abort trap: 6           mv 'temp2.bam' $smaltout

I'm pretty sure everything was installed properly and was wondering if you happen to know of a way around it. Thank you!

**Comment by apetkau** [comment]
That's no problem.  What sort of files did you use as input?  Could you try out the input test data from http://snvphyl.readthedocs.io/en/latest/user/usage/#input-data?

You can also change the setting `cleanup_job` in Galaxy to `onsuccess` or `never` to keep around temporary files generated by each job to help debug (https://github.com/galaxyproject/galaxy/blob/release_18.05/config/galaxy.yml.sample#L1622).

You can then take a look through the Galaxy log files (in `galaxy/*.log` by default) to get more details about the job and figure out where it's working directory is.  You should be able to see entries like:

```
galaxy.jobs.command_factory INFO 2018-05-29 15:06:46,622 Built script [/export/galaxy-central/database/job_working_directory/000/103/tool_script.sh] for tool command [PACKAGE_BASE=/export/tool_deps/smalt/0.7.5/nml/smalt_map/62faa1906fd7; export PACKAGE_BASE; . /export/tool_deps/smalt/0.7.5/nml/smalt_map/62faa1906fd7/env.sh; PACKAGE_BASE=/export/tool_deps/samtools/0.1.19/nml/smalt_map/62faa1906fd7; export PACKAGE_BASE; . /export/tool_deps/samtools/0.1.19/nml/smalt_map/62faa1906fd7/env.sh; bash /shed_tools/irida.corefacility.ca/galaxy-shed/repos/nml/smalt_map/62faa1906fd7/smalt_map/smalt_map.sh /export/galaxy-central/database/files/000/dataset_130.dat /export/galaxy-central/database/files/000/dataset_131.dat bam  2 /export/galaxy-central/database/files/000/dataset_41.dat /export/galaxy-central/database/files/000/dataset_42.dat  -o /export/galaxy-central/database/files/000/dataset_134.dat  -f "bam"    -n ${GALAXY_SLOTS:-2}  -l pe      -i "1000"  -j "20"    -r "1"    -y "0.5"]
```

The file `/export/galaxy-central/database/job_working_directory/000/103/tool_script.sh` is what gets run by Galaxy, and the directory `/export/galaxy-central/database/job_working_directory/000/103/working` is where Galaxy runs this tool.  So, you should be able to do the following to re-run the tool yourself on the command-line.

```bash
cd /export/galaxy-central/database/job_working_directory/000/103/working
/export/galaxy-central/database/job_working_directory/000/103/tool_script.sh
```

There may be differences in this exact directory structure depending on the version of Galaxy you use however.  I hope this helps you to debug.

**Comment by PHemarajata** [comment]
Hi, for some reason I couldn't find any of those directories in my MacOS installation. However, the problem may be due to some error in providing collection of paired reads as input for smalt. Please see below. I prepared my reads as usual (tried both untrimmed and trimmed), and every the test data didn't work. Thank you!

Input Parameter | Value | Note for rerun
-- | -- | --
What is the library type? | collections |  
**Paired-end Fastq collection | No dataset collection. |**  
Pair Type | Illumina paired-end (short inserts) |  
SMI index | 1: SMI |  
SMA index | 2: SMA |  
Mincover | Empty. |  
Scordiff | Empty. |  
Format | bam |  
Bam Options | Nothing selected. |  
Distribution insert sizes |   |  
Maximum insert size (only in paired-end mode). | 1000 |  
Minimum insert size (only in paired-end mode). | 20 |  
Sets an absolute threshold of the Smith-Waterman scores. | Empty. |  
Sets a base quality threshold (0 <= minbasq <= 10, default 0) | Empty. |  
If the there are multiple mappings with the same best alignment score report one picked at random. | 1 |  
Smith-Waterman scores are complexity weighted. | False |  
This flag triggers a more exhaustive search for alignments at the cost of decreased speed | False |  
Sets an identity threshold for a mapping to be reported (default: 0). | 0.5

**Comment by apetkau** [comment]
I suspect the issue of not finding a dataset collection when re-running smalt is unrelated, though I'm not sure why it does not pick up the dataset collection.

The `smalt` command that was run by the application is in the error message above:

```
smalt map -o /Users/peerahemarajata/galaxy/database/files/000/dataset_86.dat -f bam -n 1 -l pe -i 1000 -j 20 -r 1 -y 0.5 temp /Users/peerahemarajata/galaxy/database/files/000/dataset_3.dat /Users/peerahemarajata/galaxy/database/files/000/dataset_4.dat
```

You can verify it's passing the paired-end reads correctly by taking a look at the files `/Users/peerahemarajata/galaxy/database/files/000/dataset_3.dat` and `/Users/peerahemarajata/galaxy/database/files/000/dataset_4.dat`.

If those look good, you can try running `smalt` yourself on the command line to see if you get the same error.  If you can find the file `package_smalt_0_7_5/2d9c0c15a51e/env.sh` someplace in the Galaxy data (possibly under `galaxy/database/dependencies/`) you could load up the exact environment used by Galaxy which contains `smalt`:

```
source package_smalt_0_7_5/2d9c0c15a51e/env.sh
```

If you can do this, you can test out smalt with something like:

```
smalt index -k 13 -s 6 index_name reference.fasta
smalt map -o output.bam -f bam -n 1 -l pe -i 1000 -j 20 -r 1 -y 0.5 index_name filepair_1.fastq filepair_2.fastq
```

Documentation is at https://www.sanger.ac.uk/science/tools/smalt-0#learn-and-support

**Comment by apetkau** [comment]
I am closing this issue both because it is old but also because we have upgraded the SNVPhyl pipeline, which means the `smalt` command has been updated in Galaxy and so much of the information here is a out of date.
