### ISSUE TITLE
SNVPhyl pipeline has some broken tools in Galaxy backend for our 0.14.1 IRIDA install

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [phac-nml/irida#4]
I was wondering if there are some "latest" instructions on installing the galaxy tools for SNVPhyl?  Or has none of that changed in the fall?

Thanks,

Damion

**Comment by Public-Health-Bioinformatics** [comment]
Cancel that!  SNVPhyl jobs are failing but not because of broken tools.  I mistakenly looked at a SNVPhyl 1.0 workflow.

**Comment by apetkau** [comment]
Thanks.

**Comment by Public-Health-Bioinformatics** [comment]
So I see in my paster.log galaxy file that galaxy is missing a tool when we try to run a SNVPhyl job.  I'm lost since it seems like an example SNVPhyl 3 workflow has all its bits and pieces but I can't tell since there are a hundred workflows in the cdcgalaxyworkflow user's workflows list and I don't know  what to check.  This is the error at bottom:
...
galaxy.managers.collections_util DEBUG 2017-01-20 20:31:18,755 Validating 2 element identifiers for collection creation.
galaxy.managers.collections DEBUG 2017-01-20 20:31:18,791 Created collection with 4 elements
127.0.0.1 - - [20/Jan/2017:20:31:18 -0700] "POST /api/histories/3aa0b92f6f53ad91/contents?key=3cf7b5e253034a3b914bef05efb28fc0 HTTP/1.1" 200 - "-" "Java/1.8.0_65"
galaxy.tools.actions.upload_common INFO 2017-01-20 20:31:19,473 tool upload1 created job id 6879
127.0.0.1 - - [20/Jan/2017:20:31:19 -0700] "POST /api/tools?key=3cf7b5e253034a3b914bef05efb28fc0 HTTP/1.1" 200 - "-" "Java/1.8.0_65"
galaxy.jobs DEBUG 2017-01-20 20:31:19,610 (6879) Working directory for job is: /scratch/galaxy/job_working_directory/006/6879
galaxy.jobs.rules.DynamicToolDestination DEBUG 2017-01-20 20:31:19,646 Running config validation...
galaxy.jobs.rules.DynamicToolDestination DEBUG 2017-01-20 20:31:19,647 Finished config validation.
127.0.0.1 - - [20/Jan/2017:20:31:19 -0700] "GET /api/histories/3aa0b92f6f53ad91/contents?key=3cf7b5e253034a3b914bef05efb28fc0 HTTP/1.1" 200 - "-" "Java/1.8.0_65"
galaxy.jobs.rules.DynamicToolDestination INFO 2017-01-20 20:31:19,648 No virulence factors database
galaxy.jobs.rules.DynamicToolDestination DEBUG 2017-01-20 20:31:19,649 Tool 'upload1' not specified in config. Using default destination.
galaxy.jobs.rules.DynamicToolDestination DEBUG 2017-01-20 20:31:19,649 Running 'upload1' with 'sabin'.
galaxy.jobs.handler DEBUG 2017-01-20 20:31:19,651 (6879) Dispatching to drmaa runner
127.0.0.1 - - [20/Jan/2017:20:31:19 -0700] "GET /api/histories/3aa0b92f6f53ad91/contents/271ba756bfeab0d0?key=3cf7b5e253034a3b914bef05efb28fc0 HTTP/1.1" 200 - "-" "Java/1.8.0_65"
galaxy.jobs DEBUG 2017-01-20 20:31:19,778 (6879) Persisting job destination (destination id: sabin)
galaxy.jobs.handler INFO 2017-01-20 20:31:19,823 (6879) Job dispatched
galaxy.web.framework.decorators ERROR 2017-01-20 20:31:19,927 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/opt/galaxy/lib/galaxy/web/framework/decorators.py", line 251, in decorator
    rval = func( self, trans, *args, **kwargs)
  File "/opt/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 199, in create
    populate_state=True,
  File "/opt/galaxy/lib/galaxy/workflow/run.py", line 21, in invoke
    return __invoke( trans, workflow, workflow_run_config, workflow_invocation, populate_state )
  File "/opt/galaxy/lib/galaxy/workflow/run.py", line 60, in __invoke
    modules.populate_module_and_state( trans, workflow, workflow_run_config.param_map )
  File "/opt/galaxy/lib/galaxy/workflow/modules.py", line 1068, in populate_module_and_state
    step_errors = module_injector.inject( step, step_args=step_args, source="json" )
  File "/opt/galaxy/lib/galaxy/workflow/modules.py", line 1046, in inject
    raise MissingToolException()

All the file uploads/associations for the job seem to be set up ok, but nothing after that.
Any ideas?

**Comment by apetkau** [comment]
Could you check the SNVPhyl version 1.0 workflows (listed under **Galaxy Workflows** at http://snvphyl.readthedocs.io/en/latest/install/versions/) by importing into Galaxy and seeing if any tools are missing?

Two possibilities I can think of right now for why you see this error are:
1. Some tools in the SNVPhyl workflow failed to install, so you may have to re-install them (from the SNVPhyl tool suite seen in the above link).
2. You upgraded from an older version of IRIDA and did not install the upgraded SNVPhyl tool suite (if you upgraded from 0.11.0 or below this will have happened, see https://github.com/phac-nml/irida/blob/development/UPGRADING.md).

**Comment by Public-Health-Bioinformatics** [comment]
Thanks, Aaron, the SNVPhyl tool suite upgrade in step #2 did the trick.  I missed that in doing a .war upgrade.  Yay!

Damion

**Comment by apetkau** [comment]
Awesome.  I'm glad it worked.  I'm closing this issue.
