### ISSUE TITLE
Announcements Upgrade

### ISSUE THREAD

**Issue by joshsadam** [phac-nml/irida#419]
## Describe your idea for a new feature
* Re-develop the way announcements are created to include a **title** and **content** within the administrator panel.
* On the IRIDA users page, have an icon on the menu with a badge for the number of unread announcements.  Clicking on the icon would reveal a dropdown listing the unread announcements by title.  Clicking on the title would open the full announcement in a modal window (this would mark the announcement as read).
* Administrators could mark an announcement as a "priority" announcement, which would immediately open the announcement into a modal window when the user logs in. This modal should not be dismissable by keyboard. (this feature moved to #913)

## Describe how you would access this feature?
* The creating a new announcement should be accomplished through a newly developed admin console (see #105)
* Listing announcements should within the navigation bar on the users page.

## Additional information
Add any other context, files, or screenshots about the feature request here.

**Comment by tom114** [comment]
Added issue #913 to track automatically displaying high priority announcements. Removing from this issue for clarity.
