### ISSUE TITLE
Allow customization of the brand of IRIDA

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#423]
## Describe your idea for a new feature

Allow different installations of IRIDA to customize the brand.

## Describe how you would access this feature?

Maybe some files (images/html/text) placed in `/etc/irida` which will override the default brand.

## Additional information

An example of the page people would like to change:

![image](https://user-images.githubusercontent.com/200517/60725602-cf37be80-9f39-11e9-9ffd-2e686c53d004.png)

**Comment by joshsadam** [comment]
Since the login in page is completely configurable now, I am going to close this issue.
