### ISSUE TITLE
Option to email only on pipeline failure

### ISSUE THREAD

**Issue by dorbarker** [phac-nml/irida#434]
## Describe your idea for a new feature
Add an option to email the user only if a pipeline fails

## Describe how you would access this feature?
An additional checkbox, *Receive Email upon Failure* on the pipeline submission page to email the user on pipeline errors only.

## Additional information
Like a fool, I submitted some 2000+ samples and checked the *Receive Email upon Completion* checkbox. I had expected a single email when all samples finished, but one email is sent per sample.

That was completely a misunderstanding on my part, but really what I was interested in by checking the box was being notified if any of a large number of samples moving through the assembly pipeline exited abnormally.

An option to be emailed for errors only highlights the atypical case (a sample needs additional attention from the user) versus the usual outcome of a pipeline (a sample is complete and does not need further attention at the moment).

Related to #286

**Comment by apetkau** [comment]
Thanks for the suggestions @dorbarker :+1:. Receiving many many emails is never a good time.
