### ISSUE TITLE
Dynamic source parameter for launch page

### ISSUE THREAD

**Issue by glwinsor** [phac-nml/irida#44]
I have the IRIDA development 0.22.0 snapshot running on our test server at SFU. I'm trying to customize the input on the IslandViewer workflow launch page so that a reference accession is mandatory input.  I've updated the irida_workflow.xml to include

```
<parameter name="islandviewerclient-accession" required="true">
<choices><choice name="NC_011083" value="NC_011083.1"/></choices>
<toolParameter toolId="testtoolshed.g2.bx.psu.edu/repos/glwinsor/islandviewerclient/islandviewerclient/0.1.0" parameterName="accession"/>
 </parameter>
```

where it was previously written as:

```
<parameter name="islandviewerclient-accession" defaultValue="">
<toolParameter toolId="testtoolshed.g2.bx.psu.edu/repos/glwinsor/islandviewerclient/islandviewerclient/0.1.0" parameterName="accession"/>
 </parameter>
```

I also added an entry in the messages_en.properties file to include:

`pipeline.parameters.islandviewerclient.accession.NC_011083=Salmonella enterica subsp. enterica serovar Heidelberg str. SL476, complete genome`

After doing this and restarting tomcat, I no longer see an option for entering the reference accession (on the main launch page nor under the default parameters). However, if I select one of my previously saved default configurations where I specified accession, the accession box with the expected value appears under the default settings. 

Am i missing any other settings for the configuration?

**Comment by apetkau** [comment]
That's awesome 😄 

Hmm... I'm not too sure why the option is disappearing, but then re-appearing after you select saved parameters.  It sounds like it could be related to caching old Javascript files though.  Have you tried clearing out the browser cache and then re-logging into IRIDA?
