### ISSUE TITLE
Add pipeline troubleshooting guide

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#442]
## Describe your idea for a new feature
Add a troubleshooting guide for IRIDA pipelines to assist administrators.

## Describe how you would access this feature?
This would be part of the IRIDA documentation and would assist IRIDA administrators to troubleshoot failures in IRIDA pipelines as well as explain how to extract information from the underlying Galaxy instance.

## Additional information
N/A

**Comment by tom114** [comment]
Fixed in #443
