### ISSUE TITLE
Autofill in Chrome prevents user details from being updated

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#445]
## Describe the bug
If you create a new **User** in IRIDA and select the Chrome option to save the username/password details you've filled in:

![image](https://user-images.githubusercontent.com/200517/62392392-f2e82780-b52c-11e9-9b3a-2149816998e5.png)

Next time you try and modify the user details, the **username** is automatically populated in the **email** field:

![image](https://user-images.githubusercontent.com/200517/62392487-2b880100-b52d-11e9-90cc-f75310c4e1f7.png)

This prevents users from modifying details about a user until they delete the username from the email box.

## Steps to reproduce the problem
1. Create a new user in IRIDA. When Chrome asks, make sure to save the username/password.
2. Try to edit the user details, Chrome will autofill in the email and password boxes with the username and password.

## Expected behaviour
I expected Chrome to either autofill in the "username" box with the username (instead of the email). Or, otherwise, to not autofill credentials in this page at all (perhaps to disable saving credentials on this page, not sure if this is possible).

## Additional context
N/A

**Comment by tom114** [comment]
In theory it should be an easy fix. I think we could add a `autocomplete="off"` to the form tag here. https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by joshsadam** [comment]
Looks good, I will get it done.
