### ISSUE TITLE
Is it possible to reorder pipeline output files

### ISSUE THREAD

**Issue by glwinsor** [phac-nml/irida#45]
We chatted about this during last week's hackathon. Would it be possible to order the list of output files that appear under "Preview" tab after the analysis completes?  For example, when the IslandViewer analysis pipeline completes, it would be ideal to show the final two output files at the top of the list (considering they are the most relevant).  It would make sense to base the order on when they were created (i.e. reverse order based on time they were created). It also came up that the order could be specified based on the order the outputs appear in the irida_structure.xml file.

**Comment by peterk87** [comment]
Hey @glwinsor, I'm updating the assembly and annotation pipeline and I've added output preview ordering based their order in the IRIDA workflow XML file. I could spin that small change off into a separate merge request so that it shows up in dev branch sooner.

**Comment by glwinsor** [comment]
That sounds great! Please do and I can test things out for you.

**Comment by peterk87** [comment]
Hi @glwinsor I've made a PR with the changes necessary to render the output previews in `irida_workflow.xml` `<outputs>` order in #46. It hopefully shouldn't be too hard to test the changes as they're fairly minor.

**Comment by glwinsor** [comment]
Thanks Peter,
I just tried out the new changes and can confirm my IslandViewer output is sorted properly.  Looks much better!
