### ISSUE TITLE
Remove angular ui

### ISSUE THREAD

**Issue by joshsadam** [phac-nml/irida#477]
## What needs changed?
Angular UI is used on multiple pages to handle thing like modals, dropdown menus, etc...  It is being removed from IRIDA as its major dependency is bootstrap.

## How does it work now?
Angular UI is a combination between angularjs and bootstrap allowing for dynamic creation of modals, dropdowns, etc...

## How should it work?
Replace with Ant Design.

## Additional information
This will need to be a part of a larger refactor.  Please add any pages that currently depend on this here.

**Comment by tom114** [comment]
Partially done in #559

**Comment by joshsadam** [comment]
This has been removed for a while now.  Could not find PR with it. No longer in `package.json`
