### ISSUE TITLE
Exporting to ngsArchiveLinker.pl or to CSV fails with >= 330 samples 

### ISSUE THREAD

**Issue by dorbarker** [phac-nml/irida#510]
## Describe the bug
Uploading a sample sheet with 330 or more samples to filter-by-file and then trying to export the results to ngsArchiveLinker.pl or to a CSV file will cause it to hang. Attempting to export 329 or fewer works as expected.

## Steps to reproduce the problem
1. Create non-working example sheets by running:
`shuf samples.txt | head -n 330 > samples_330.txt`
2. Use these to filter-by-file on Project 944 "FNC Campylobacter"
3. Attempt to export to command-line or to CSV
4. Repeat steps 1-3, but using 329 samples for a working-as-expected example

## What were you doing when you encountered the problem?
Trying to filter [Project 944](http://ngs-archive.corefacility.ca/irida/projects/944) in order to symlink samples found in `samples.txt` to Waffles 

## Expected behaviour

A ngsArchiveLinker.pl command should be generated in a dialog box, or a CSV should be made available for download.

A temporary workaround is to link every sample in the project, and then delete the samples that are not of interest.

## Additional context
[samples.txt](https://github.com/phac-nml/irida/files/3806185/samples.txt)
[samples_330.txt](https://github.com/phac-nml/irida/files/3806184/samples_330.txt)
[samples_329.txt](https://github.com/phac-nml/irida/files/3806183/samples_329.txt)

**Comment by tom114** [comment]
I'm going to guess this has something to do with the size of the request URL params coming back to IRIDA.  If this is the case we would just switch it to a POST instead of a GET.  I confirmed that the server request URL is currently a GET.
