### ISSUE TITLE
Inconsistent behaviour between the Sample Tab's search box and filter-by-file

### ISSUE THREAD

**Issue by dorbarker** [phac-nml/irida#513]
## Describe the bug
When entering a strain name into the search box on the Samples tab, dashes and underscores are treated as equivalent. 

When filtering by file, underscores and dashes are treated as strictly different. 

This inconsistent behaviour could (and has) lead to samples being silently skipped when filtering by file. 

## Steps to reproduce the problem

1. Open [Project 1234 "GenomeAlbertaProject"](http://ngs-archive.corefacility.ca/irida/projects/1234)
2. Attempt to filter by file using `samples_with_underscores.txt`
    - This will return no samples
3. Attempt to filter by file using `samples_with_dashes.txt`
    - This will return ten samples
4. In the search box, enter `12-105634-0022`
    - This returns the strain as expected
5. In the search box, enter `12_105634_0022`
    - This treats underscores and dashes as equivalent, and returns `12-105634-0022`

## Expected behaviour
Either dashes and underscores should be treated as distinct everywhere or equivalent everywhere.

## Additional context
[samples_with_dashes.txt](https://github.com/phac-nml/irida/files/3810892/samples_with_dashes.txt)
[samples_with_underscores.txt](https://github.com/phac-nml/irida/files/3810893/samples_with_underscores.txt)

**Comment by deepsidhu85** [comment]
Fixed in #550
