### ISSUE TITLE
Pipeline with single-end reads sample as an input

### ISSUE THREAD

**Issue by aknijn** [phac-nml/irida#53]
I'm trying to get a pipeline working with single-end reads sample as an input. The pipeline has been defined but when a single-end reads sample is added to the cart and the pipeline is selected, the pipelines page doesn't load correctly and the catalina.out file logs the following error:

ERROR org.thymeleaf.TemplateEngine:1136 - [THYMELEAF][http-bio-8080-exec-4] Exception processing template "pipelines/types/generic_pipeline": Exception evaluating SpringEL expression: "join.getObject()" (template: "pipelines/types/generic_pipeline" - line 265, col 53)
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "join.getObject()" (template: "pipelines/types/generic_pipeline" - line 265, col 53)
....
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1004E:(pos 5): Method call: Method getObject() cannot be found on ca.corefacility.bioinformatics.irida.model.sequenceFile.SingleEndSequenceFile type

When a paired-end reads sample is added to the cart and the same pipeline selected, the pipeline page loads fine but obviously the message "This sample does not contain any files that can be run on this pipeline." is shown.

**Comment by apetkau** [comment]
Just want to comment that our pipeline plugin code got merged into our `development` branch, so those two branches above aren't available anymore. Our most up to date documentation for pipeline plugins can be found at https://github.com/phac-nml/irida/blob/development/doc/developer/tools/pipelines/index.md

**Comment by aknijn** [comment]
Thank you for the update, this will avoid recompiling everything in order to add a pipeline, very nice.
As for the single-end reads sample as an input, do you have any news on that?

**Comment by tom114** [comment]
This issue was completed in 20.05.  Closing.
