### ISSUE TITLE
Cannot download multiple analysis output files

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#534]
## Describe the bug
Cannot download multiple analysis output files. Instead the following exception is thrown:

```
02 Dec 2019 09:19:22,018 ERROR ca.corefacility.bioinformatics.irida.ria.web.errors.ExceptionHandlerController:117 - Failed to
convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatExceptio
n: For input string: "prepare"
org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.Stri
ng' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "prepare"
        at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedVal
ueMethodArgumentResolver.java:115)
        at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgument
ResolverComposite.java:78)
...
Caused by: java.lang.NumberFormatException: For input string: "prepare"
```

## Steps to reproduce the problem
1. Share analysis submissions with project.

    ![image](https://user-images.githubusercontent.com/200517/69971269-3ce61780-14e5-11ea-91e8-9f38cd10b374.png)

2. In the project **Analysis > Shared Single Sample Analysis Outputs** page, try to select and download multiple files.

    ![image](https://user-images.githubusercontent.com/200517/69971403-728b0080-14e5-11ea-8427-e3f1573601e9.png)

3. The download will fail and the above exception will be thrown.

## Expected behaviour
I expected to be able to download a zip archive of all the output files I selected.

## Additional context
None.

**Comment by deepsidhu85** [comment]
Fixed in #539
