### ISSUE TITLE
User's analysis-outputs download page does not work

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#535]
## Describe the bug
The user's analysis-outputs download page does not work. Trying to go to the page gives me:

![image](https://user-images.githubusercontent.com/200517/69971853-27bdb880-14e6-11ea-94ac-4d871a4b0ef2.png)

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. In IRIDA, go to **Analyses > Your Analyses**
2. You will get the above error.

## Expected behaviour
I expected to be brought to the proper page.

## Additional context
None.

**Comment by deepsidhu85** [comment]
Fixed in #539
