### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by innovate-invent** [phac-nml/irida#592]
## Describe the bug
I am currently following the IRIDA plugin tutorial.
Installation of IRIDA fails with this error:
```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project irida: Fatal error compiling: invalid flag: --release
```
I tried both the dev and master branches.

## Steps to reproduce the problem

```sh
git clone https://github.com/phac-nml/irida.git
cd irida/lib
./install-libs.sh
cd ..
mvn clean install -DskipTests
```

## Expected behaviour

Compile successfully

**Comment by apetkau** [comment]
Hello @innovate-invent. Which version of Java are you using? You can print with `mvn -version`.Note that the latest version of IRIDA requires Java 11 (previous versions could work with Java 8). So this may be the source of your issue.

**Comment by innovate-invent** [comment]
I tried switching to openjre 11 with no success:
```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project irida: Fatal error compiling: error: release version 11 not supported
```

**Comment by innovate-invent** [comment]
Looks like maven can't tell the difference between the JDK and the JRE. I didn't have jdk11-openjdk installed.

**Comment by kbessonov1984** [comment]
Compilation will only work if one installs Java Development Kit (JDK) and not JRE as a Java development files are needed for the compiler.

1. In Ubuntu install Java 11 **JDK**
```
apt-get install openjdk-11-jdk
```
2. If more than one Java is installed, select the right version via `update-alternatives`
```
update-alternatives --config java
 Selection    Path                                            Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1109      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1109      manual mode
  2            /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java   1071      manual mode
  3            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1069      manual mode
```
2. Make sure `mvn` is using right Java version
```
mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /root/apache-maven-3.3.9
Java version: 11.0.5, vendor: Ubuntu
```
3. Try to compile again
```
mvn install -Dskiptests

```
