### ISSUE TITLE
IRIDA and GALAXY 

### ISSUE THREAD

**Issue by rat-codes** [phac-nml/irida#6]
Hi Aaron,
I have three questions to regarding addition of new workflow.

1) This is another issue I didn't know how to handle. Now, I am able to successfully create a worfklow, and set parameters (through irida_workflow.xml file and messages_en_properties). My pipelines involves the following tools for now, 
Workflow: BWA -> SAMTools -> GATK -> MPileup ->BCFTools view
Input & outptut: Dataset Collections

IRIDA is able to submit the analysis successfully (uploads dataset collection, parameters and workflow is run successfully at GALAXY end), however, it throws error while trying to transfer the output from GALAXY to IRIDA as below, which I guess is due to collection as output

```
12 May 2017 14:40:00,060 ERROR ca.corefacility.bioinformatics.irida.service.analysis.execution.AnalysisExecutionServiceAspect:63 - Error occured for submission: AnalysisSubmission [id=5, name=BWAtoBCFTools_20170512, submitter=admin, workflowId=8cee8752-df1f-45a9-887c-8c77450bb093, analysisState=COMPLETING, analysisCleanedState=NOT_CLEANED] changing to state ERROR
ca.corefacility.bioinformatics.irida.exceptions.galaxy.GalaxyDatasetNotFoundException: dataset for file output not found in Galaxy history 3cc0effd29705aa3
        at ca.corefacility.bioinformatics.irida.pipeline.upload.galaxy.GalaxyHistoriesService.getDatasetForFileInHistory(GalaxyHistoriesService.java:284)
        at ca.corefacility.bioinformatics.irida.service.analysis.workspace.galaxy.AnalysisWorkspaceServiceGalaxy.getAnalysisResults(AnalysisWorkspaceServiceGalaxy.java:378)
        at ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxyAsync.transferAnalysisResults(AnalysisExecutionServiceGalaxyAsync.java:238)
        at ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxyAsync$$FastClassBySpringCGLIB$$fc2d896.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:718)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:58)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:108)
        at org.springframework.security.concurrent.DelegatingSecurityContextCallable.call(DelegatingSecurityContextCallable.java:60)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

2) How to add the list of project organism in our instance? Galaxy provides in-built genome index, and hence we thought of not having to upload the reference everytime. For now, I am skipping the reference paramters in my workflow, so the default setup in the galaxy workflow (irida_workflow_structure.ga) is used. 

3) Is it possible for IRIDA to download the output datasets that are renamed at GALAXY side based on input files(Example: #{fastq_input1}. This is actually available in recent version of GALAXY for paired-end collections. But, when I try to connect IRIDA to latest GALAXY, the default pipelines encounter lot of errors and paused for ever). 

Please let me know your suggestions. 

Thanks a lot!

Best,
Aarthi

**Comment by apetkau** [comment]
Hello Aarthi,

1. Does the output file name in the IRIDA Workflow Description XML match the file name in Galaxy.  The error message you are getting, in particular `dataset for file output not found in Galaxy history` suggests that IRIDA is looking for a file named 'output' (defined in the XML file https://irida.corefacility.ca/documentation/developer/tools/pipelines/#b-workflow-description), but that this file is not found in Galaxy.  In Galaxy, you would most likely have to use the **Rename Dataset** option to name the file properly, as shown in https://irida.corefacility.ca/documentation/developer/tools/pipelines/#b-output-format.

    If the file names match up in both cases, can you verify that when the workflow is run by IRIDA it does show a file named 'output' in the Galaxy History?

2. There is currently no way to link up Galaxy's built-in genome indexes with IRIDA other than to have a particular organism hard-coded in your workflow. The reference files we have been using we manage within IRIDA and upload to Galaxy as they tend to be limited in number and size.  However, we will consider providing better support for this feature.

3. No it is not possible.  IRIDA expects output datasets to have a specific and fixed name.  This is something we will consider in the future, though, as we focus more time on improving the pipeline development system of IRIDA.

I hope this helps you out,

Aaron

**Comment by rat-codes** [comment]
Hi Aaron, 

Thanks for the detailed answers. For now, I am setting the genome index as default in the workflow file, so we can skip the reference upload. 

Sorry to have missed that detail. I have renamed the datasets in GALAXY and re-run it. But still IRIDA throws the error as in the attached file. 

The output section in my irida_workflow.xml file looks like this 
```
        <outputs>
                <output name="GATK-IndelRealigner" fileName="gatk_realigned.bam" />
                <output name="mpileup_output" fileName="mpileup_out.bcf" />
                <output name="bcftools_view_output" fileName="bcftools_view.vcf" />
        </outputs>
```

And through bioblend, I can see these files in the histories using 
`hc.show_history('500665cb113baad6',contents=True)`

> WBB280_S26_L001_R2_001.fastq 021db96d9b3dc9ea
> WBB280_S26_L001_R1_001.fastq b84c3be6e81b396e
> irida_sequence_files_paired c2f15bb285119094
> Map with BWA-MEM on data 2 and data 1 (mapped reads in BAM format) 102821ce700f9481
> Map with BWA-MEM across collection 3 4a31abf1f877a79d
> GATK - RealignerTargetCreator on data 4 (GATK intervals) ed576498e08c33e4
> GATK - RealignerTargetCreator on data 4 (log) 598fe0da16abf5a9
> GATK across collection 5 6df0b7b066ddc4c9
> GATK across collection 5 b1208393f3608833
> gatk_realigned.bam 32e7d30ce9d8fe9e
> GATK - IndelRealigner on data 6 and data 4 (log) e048c0277ff9d0b7
> GATK across collection 5 and collection 8 d796ca8e1687a54b
> GATK across collection 5 and collection 8 06cf32e9aa8aad75
> mpileup_out.bcf d1efc9f032edaaf4
> MPileup on data 10 (log) 472adaae16803632
> MPileup across collection 12 34c3e3c01e1a37f4
> MPileup across collection 12 e96c6ce43a3d239a
> bcftools_view.vcf fa988962518d059a
> bcftools view across collection 16 53fb5c5113d9beb7


Actually the output is a collection, I am not sure if IRIDA thinks it as 'dataset' instead and hence the problem. I have gone through the _bioblend_ API for galaxy, and cannot find a method to download collections (except through manually traversing each element in the collection and downloading) and I guess IRIDA uses a _'bioblend.galaxy.datasets.DatasetClient.download_dataset'_ equivalent in _blend4j_. 
This is more like trying to download the BAM collection (smalt_map) from SNVPhyl pipeline to IRIDA side.

Appreciate your help! Thanks a lot for looking into this!


[catalina_out.txt](https://github.com/phac-nml/irida/files/1007191/catalina_out.txt)

Best,
Aarthi

**Comment by apetkau** [comment]
According to the attached file, all the datasets are properly downloaded and saved.  This is what the messages like `Target is [/home/sphadmin/irida_datadir_local/output/20/0/bcftools_view.vcf]` are saying.  

The error you are encountering appears be related to saving your custom analysis object in the database:

```
org.springframework.dao.InvalidDataAccessApiUsageException: Unknown entity: ca.corefacility.bioinformatics.irida.model.workflow.analysis.AnalysisBwaToBcftools; nested exception is java.lang.IllegalArgumentException: Unknown entity
...
        at ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxyAsync.transferAnalysisResults(AnalysisExecutionServiceGalaxyAsync.java:241)
```

The particular code I've highlighted in the stack trace corresponds to https://github.com/phac-nml/irida/blob/master/src/main/java/ca/corefacility/bioinformatics/irida/service/analysis/execution/galaxy/AnalysisExecutionServiceGalaxyAsync.java#L241, where the following is being run:

Can you make sure your class `AnalysisBwaToBcftools` looks similar to https://github.com/phac-nml/irida/blob/master/src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/AnalysisSISTRTyping.java#L15,

That is, is annotated with something like:

```java
@Entity
@Table(name = "analysis_sistr_typing")
public class AnalysisSISTRTyping extends Analysis {
```

Can you also make sure you have the appropriate database upgrade scripts to add a new table for your analysis type.  This should like similar to https://github.com/phac-nml/irida/blob/master/src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/0.16.0/sistr.xml#L9.  That is, there is a `createTable` tab like:

```xml
		<createTable tableName="analysis_sistr_typing">
			<column name="id" type="bigint(20)">
				<constraints primaryKey="true" nullable="false"
					referencedTableName="analysis" referencedColumnNames="id"
					foreignKeyName="FK_ANALYSIS_SISTR_TYPING_ANALYSIS" />
			</column>
		</createTable>
```

Let me know if this doesn't fix your issue.

**Comment by rat-codes** [comment]
Thanks Aaron. Adding the '@Entity' lines did fix it up. I guess I should also add an empty constructor as shown in your link, otherwise I get an 'No default constructor for entity' exception. But, as I said If i request IRIDA to download a collection of BAM, then I get the following error, 

> 18 May 2017 17:35:08,258 DEBUG ca.corefacility.bioinformatics.irida.service.impl.AnalysisExecutionScheduledTaskImpl:204 - Transferring results for AnalysisSubmission [id=2, name=BWAtoBCFTools_20170518, submitter=admin, workflowId=8cee8752-df1f-45a9-887c-8c77450bb093, analysisState=FINISHED_RUNNING, analysisCleanedState=NOT_CLEANED]
> analysisSubmission = AnalysisSubmission [id=2, name=BWAtoBCFTools_20170518, submitter=admin, workflowId=8cee8752-df1f-45a9-887c-8c77450bb093, analysisState=FINISHED_RUNNING, analysisCleanedState=NOT_CLEANED]
> 18 May 2017 17:35:08,370 DEBUG ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxyAsync:237 - Getting results for AnalysisSubmission [id=2, name=BWAtoBCFTools_20170518, submitter=admin, workflowId=8cee8752-df1f-45a9-887c-8c77450bb093, analysisState=COMPLETING, analysisCleanedState=NOT_CLEANED]
> 18 May 2017 17:35:08,449 ERROR ca.corefacility.bioinformatics.irida.service.analysis.execution.AnalysisExecutionServiceAspect:63 - Error occured for submission: AnalysisSubmission [id=2, name=BWAtoBCFTools_20170518, submitter=admin, workflowId=8cee8752-df1f-45a9-887c-8c77450bb093, analysisState=COMPLETING, analysisCleanedState=NOT_CLEANED] changing to state ERROR
> ca.corefacility.bioinformatics.irida.exceptions.galaxy.GalaxyDatasetException: Found 2 datasets for file bcftools_view.vcf: [b0116f2d16f57edc,d171adc4905bca99,]
>         at ca.corefacility.bioinformatics.irida.pipeline.upload.galaxy.GalaxyHistoriesService.getDatasetForFileInHistory(GalaxyHistoriesService.java:272)
>         at ca.corefacility.bioinformatics.irida.service.analysis.workspace.galaxy.AnalysisWorkspaceServiceGalaxy.getAnalysisResults(AnalysisWorkspaceServiceGalaxy.java:378)
>         at ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxyAsync.transferAnalysisResults(AnalysisExecutionServiceGalaxyAsync.java:238)
>         at ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxyAsync$$FastClassBySpringCGLIB$$fc2d896.invoke(<generated>)
>         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
>         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:718)
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
>         at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
>         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
>         at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
>         at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:58)
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
>         at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
>         at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:108)
>         at org.springframework.security.concurrent.DelegatingSecurityContextCallable.call(DelegatingSecurityContextCallable.java:60)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)

I have attached a screenshot from GALAXY. As you can see, there are two outputs for each step, and so the API call returns two dataset id for the same name. 
From _bioblend_ I can see no options to download collection, but to traverse the elements inside it and download each dataset. Is it possible to download a collection in IRIDA? Specifically, Is there a element in the XML <output> to mention the type of file and then call a respective function to handle it. 

If you could direct me to the class files, I can try to edit and test if it works for us. Sorry for being rustic in my descriptions, I have just started learning JAVA!

Thanks for your help!

Aarthi
![bwa_pipeline_completion_galaxy](https://cloud.githubusercontent.com/assets/8120708/26235855/f94ae55c-3c9f-11e7-97f0-deb64af58965.png)

**Comment by apetkau** [comment]
Hello Aarthi,

I apologize for not responding to this earlier.  There is no way to directly download a collection of files from within IRIDA, but what you could do is add another tool [bundle_collections](https://toolshed.g2.bx.psu.edu/view/nml/bundle_collections/bae199dc511f) which will compile all files in a collection to a single zip file you can then download.  Would this work for you?

Aaron

**Comment by rat-codes** [comment]
Hi Aaron, thanks for your help! I have seen this tool being used in one of your workflow steps. I will take a look at it and see how it works for us. Thanks again for all the help! 
For now, we are using bioblend to handle unique naming of each sample and download of collections. I am yet to workout the same in blend4j to integrate it better. I will close this issue.

Best,
Aarthi
