### ISSUE TITLE
Developer docs out-of-date

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#600]
## Describe the bug
The developer documentation has some out-of-date parts (such as still referring to Java 8).

## Steps to reproduce the problem
See https://irida.corefacility.ca/documentation/developer/getting-started/

## Expected behaviour
It should be mentioned that Java 11 is required. And links should point to the correct version of Spring.

## Additional context
None.

**Comment by tom114** [comment]
Changed Java 8 to 11 in developer docs in #660
