### ISSUE TITLE
Sample name not updated in cart

### ISSUE THREAD

**Issue by deepsidhu85** [phac-nml/irida#607]
## Describe the bug
Briefly describe the issue you encountered.

Sample name in the cart is not updated if the sample name is changed once it's in the cart.

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Added a sample to cart 
2. Clicked to view the cart
3. The sample name and project name were displayed for the sample
4. Updated the sample name
5. Clicked to view the cart again
6. The old sample name was still displayed

## Expected behaviour
What did you expect to happen?

I expected the sample name in the cart to be updated.

## Additional context
Additional information to help solve the problem.  Test files, screenshots, IRIDA version information can go here.

**Comment by tom114** [comment]
Confirmed this issue no longer occurs with new cart implementations.
