### ISSUE TITLE
Add ability to get partial results from a workflow early

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#67]
In particular, for the SNVPhyl pipeline, it would be nice to get a distance-based tree ahead of time.

Imported from GitLab issue #398.  Originally posted on 2016/08/18 02:04PM

**Comment by tom114** [comment]
While it's a good idea, I think this use case better fits into a Galaxy user than an IRIDA user.  If a user is looking to get different stages of their results, maybe those should be 2 separate pipelines.  Closing.
