### ISSUE TITLE
Browser file selector not allowing .fastq.gz on Mac

### ISSUE THREAD

**Issue by dfornika** [phac-nml/irida#672]
## Describe the bug
Browser won't allow user to upload `.fastq.gz` files using the 'Upload Sequence Files' button.

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Select a sample
2. From the 'Upload Files' drop-down button, select 'Upload Sequence Files'
3. Browser dialog will allow user to select `.fastq` files but not `.fastq.gz` files

## Expected behaviour
What did you expect to happen?
I expect to be able to select and upload `.fastq.gz` files from the file upload dialog that the browser presents

## Additional context
Additional information to help solve the problem.  Test files, screenshots, IRIDA version information can go here.

Using the IRIDA `development` branch on commit `639b0bbd621350d61a624279fcb6efc5fb7d29d9`
Tested in Chrome v81 and Firefox v75, both on macOS.

<img width="925" alt="Screen Shot 2020-05-01 at 4 28 25 PM" src="https://user-images.githubusercontent.com/145659/80848863-a28c1c00-8bc9-11ea-82b3-a815c2c15927.png">
<img width="791" alt="Screen Shot 2020-05-01 at 4 29 42 PM" src="https://user-images.githubusercontent.com/145659/80848870-a881fd00-8bc9-11ea-89d6-c15a1afc84f2.png">

`allowedTypes` is defined here:
https://github.com/phac-nml/irida/blob/bcefda8fa02b0aea65ea8114fa943e93487f60e3/src/main/webapp/resources/js/components/sample/SampleFileUploader.jsx#L47

...but it seems that compound extensions like `.fastq.gz` are not supported. Changing that value to `.gz` does allow `.fastq.gz` files to be uploaded.

**Comment by tom114** [comment]
Tested in Windows and Linux and it allow me to pick files.  Both in Chrome.  Going to get someone to test it on Mac here to verify.

**Comment by joshsadam** [comment]
Test and can verify that this is an issue on the Mac.  I will create a fix for it.
