### ISSUE TITLE
Submission of pipelines with large number of samples (700+) does not work

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#68]
Some tests were being done when submitting large number of samples (700+) and the submission process fails.  There's nothing in the log file I can see and it does not even make it to the stage of writing an analysis submission (so it's stuck in the code before the "Your workflow is submitted" is reached).

Could this be something in the UI @josh.adam or maybe in the time it takes to validate all 700+ samples (1400+ files)?  Pipelines with < 500 samples seem to all work still.

Imported from GitLab issue #399.  Originally posted on 2016/08/23 01:05PM

**Comment by joshsadam** [comment]
Not that I can think of, but we can play around with it next week when I am back from vacation.

Imported from GitLab.  Originally posted on 2016/08/23 02:34PM

**Comment by tom114** [comment]
Related to #192

**Comment by tom114** [comment]
Cart has had a full-scale refactor so this issue is fixed. Closing.
