### ISSUE TITLE
slight typo in command line linker

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [phac-nml/irida#7]
The text explaining the context needs a slight adjustment:

"Command-line Linker
In your terminal, go to the folder **you want to sample links contained**. Copy and paste the following command."

Should probably be: **you want links to a project's sample files to appear in**.

Also its worth saying early on that this tool is only pertinent for users who have accounts on the network share connected to the IRIDA server.  (Some might think ngsArchive.pl has mastered remote file access).

**Comment by joshsadam** [comment]
I can definitely update the wording on that, thanks.

About the linker tool only pertinent for users who have who have a network share connected to the IRIDA server, it is up to the administrator to turn that feature on and off in `src/main/resources/configuration.properties`, with the properties:

```
ngsarchive.linker.available=true
ngsarchive.linker.script=ngsArchive.pl
```

**Comment by apetkau** [comment]
You can also copy/paste and adjust those same properties in the file `/etc/irida/irida.conf`.

**Comment by Public-Health-Bioinformatics** [comment]
Ok, good to know.  I was mainly raising it as a documentation point - to have this prerequisite info added to the user documentation.

**Comment by joshsadam** [comment]
I think this issue has been addressed.  I will close this now.
