### ISSUE TITLE
Documentation on creating custom miseq runs

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#71]
Provide documentation on creating custom miseq runs for upload.  For example, how to create a `SampleSheet.csv` file, and the proper directory structure and placement of fastq files.

Imported from GitLab issue #414.  Originally posted on 2016/11/15 02:31PM

**Comment by tom114** [comment]
More useful here would be enhancements to the uploader to allow pointing to a directory of files.  That way we could stop doing the "fake" miseq run thing.

Imported from GitLab.  Originally posted on 2017/08/29 09:42AM

**Comment by tom114** [comment]
This is now covered with the new uploader at https://irida-uploader.readthedocs.io/en/latest/parsers/directory.html.  Closing
