### ISSUE TITLE
Change SNVPhyl dependency to use main Galaxy toolshed

### ISSUE THREAD

**Issue by tom114** [phac-nml/irida#713]
## What needs changed?
SNVPhyl in IRIDA currently depends on a self-hosted Galaxy toolshed that's getting old.  This is preventing IRIDA/Galaxy installs using newer Galaxy versions for running IRIDA workflows.

## How does it work now?
Galaxy is installed via the IRIDA toolshed.  See install instructions at https://irida.corefacility.ca/documentation/administrator/galaxy/pipelines/phylogenomics/.  Current toolshed location https://irida.corefacility.ca/galaxy-shed/repository/view_repository?sort=name&operation=view_or_manage_repository&f-free-text-search=snvphyl&id=abd1d96f80f452d0.

## How should it work?
SNVPhyl pipline in IRIDA should rely on the main Galaxy toolshed.  A newer version of SNVPhyl is available here https://toolshed.g2.bx.psu.edu/repository/view_repository?sort=name&operation=view_or_manage_repository&f-free-text-search=snvphyl&id=36f72188ca68ffad.

This will require updating the IRIDA workflow in https://github.com/phac-nml/irida/tree/development/src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/SNVPhyl

## Additional information
The old IRIDA toolshed may need to stay up for a period to allow for old IRIDA installs, but should be deprecated.

**Comment by apetkau** [comment]
Waiting for https://github.com/phac-nml/galaxy_tools/pull/199
