### ISSUE TITLE
Exception thrown when viewing users list as a manager

### ISSUE THREAD

**Issue by deepsidhu85** [phac-nml/irida#732]
## Describe the bug
Briefly describe the issue you encountered.

When attempting to view the Users list as a Manager the page throws an error.

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Create an account with a role of Manager
2. Login as the manager
3. Click the gear cog and then the Users menu item
4. Page throws an HTTP ERROR 500 javax.servlet.ServletException

## Expected behaviour
What did you expect to happen?

I expected to be able to see a list of users

## Additional context
Additional information to help solve the problem.  Test files, screenshots, IRIDA version information can go here.

**Comment by tom114** [comment]
Fixed in #734
