### ISSUE TITLE
Email server settings

### ISSUE THREAD

**Issue by innovate-invent** [phac-nml/irida#757]
I am looking to configure IRIDA to use an existing SMTP server to send mail. This server requires password authentication but the IRIDA config does not expose this option. Perhaps I am not understanding a limitation of the underlying framework.
There isn't any documentation that I can find surrounding the mail server configuration beyond the mention in the web.conf template.

Is it possible to add this feature?

## Additional information
https://github.com/phac-nml/irida/blob/a21c59fe30b80a3dda8fb1967463bbc4e45e2d6d/src/main/java/ca/corefacility/bioinformatics/irida/config/services/WebEmailConfig.java#L51-L57

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/mail/javamail/JavaMailSenderImpl.html#setPassword-java.lang.String-

**Comment by tom114** [comment]
Hi @innovate-invent , it looks like you're correct that the `setPassword` method is available on the `ConfigurableJavaMailSenderImpl` but it's currently being used.  Right were you mentioned in `WebEmailConfig.java` is the place I imagine it needs to be added.  I don't have a SMTP server with that configuration available to test.  If you wanted to try adding it to test your server I'd be happy to check out a PR if it works out.
