### ISSUE TITLE
add ability to prioritize users for specific analysis submissions

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#77]
Imported from GitLab issue #431.  Originally posted on 2017/03/03 03:59PM

**Comment by tom114** [comment]
Related to #430

Imported from GitLab.  Originally posted on 2017/08/30 11:44AM

**Comment by tom114** [comment]
I think we can call this done with the prioritization of automated analysis pipelines for given projects. Individual pipelines can also have their priorities changed by administrators when needed.  Closing.
