### ISSUE TITLE
Refactoring client pages

### ISSUE THREAD

**Issue by paulowenbrown** [phac-nml/irida#780]
## Describe your idea for a new feature
Currently only the client listing page is written in React. This feature involves translating the other client pages (create, edit, and details) over to React. This will allow these client pages to fit into the new single-page admin panel.

## Describe how you would access this feature?
Accessed by first navigating to the admin panel through pressing its button on the top right of the navbar. Then by clicking the Clients button on the panel's side menu. This will open the clients listing page within the panel, where you can press on any of the entries to view its new details page, which includes the edit and delete features.

## Additional information
This issue has already been started on the following branch: https://github.com/phac-nml/irida/tree/admin-client-refactor
There are a few remaining portions that have yet to be completed/fixed:

- [x] **AddClient's required server data and client creation.** AddClient requires data from the server, namely lists to choose from, that are necessary for creating a client. Currently the server provides it to the front end via model.addAttribute(), and then it is used with window.PAGE.variableName. It is not working with the current set up and I couldn't figure out any alternatives. In addition, the call to create a client does not work either. I don't know if this is due to lack of fields provided because of the aforementioned issue, or because the call itself is wrong.

- [x] **Editing of client details** This is partially complete. You can successfully edit the clientId and registeredRedirectUri, but the other fields have not been completed. This is due to the differences between the create client fields on the front end and how it is stored on the back end. The IridaClientDetails object will need to be changed to store the exact fields that need to be able to updated on the front end, instead of modifying them in a way in which they cannot be updated.

- [x] **Removal of a client** The current call to remove a client gives a 500 error, I couldn't figure out a way to make it work.

- [x]  **Client Tokens page** It will properly remove tokens, however due to the issue with the client details object, I couldn't get the client token info on the page. Once the above issue is rectified this one come naturally.

- [x] **Styling, specifically hiding certain fields and notifications** As I was focused on getting the data to properly show and actions to work as intended first, I ran out of time for certain styling aspects. On the addition modal I didn't do the hiding of fields, and some of the notifications on the pages will need to be provided the correct parameters to display as intended.

**Comment by joshsadam** [comment]
This has been completed with #794
