### ISSUE TITLE
Cannot export to SRA if sequences were generated on some sequencing platforms

### ISSUE THREAD

**Issue by dorbarker** [phac-nml/irida#802]
## Describe the bug
You can't export to SRA if your samples were sequenced using a Illumina NextSeq (and probably other platforms). When preparing to export samples from IRIDA to SRA, you're required to indicate the **Instrument Model** used. "Illumina NextSeq" is not a selectable option. This variable has a restricted vocabulary and no way of overriding this restriction. If the vocabulary doesn't reflect the instruments used by the institution, exporting samples to SRA is a non-starter.

## Expected behaviour
That I could export to SRA samples that were sequenced at the NML Core Facility on an Illumina NextSeq. 

## Additional context
Related to #186

**Comment by dorbarker** [comment]
It occurs to me that this is may be better managed via a config file than [a hard-coded enum](https://github.com/phac-nml/irida/blob/master/src/main/java/ca/corefacility/bioinformatics/irida/model/export/NcbiInstrumentModel.java).

That way an institution can restrict the available sequencers to what they actually have if they choose, as well as being able to add any newly acquired instruments without having to edit and rebuild IRIDA's src.

**Comment by ericenns** [comment]
This was added in 22.03 release.
