### ISSUE TITLE
Cannot remove sequencing runs.

### ISSUE THREAD

**Issue by joshsadam** [phac-nml/irida#808]
## Describe the bug
The "Remove" sequencing run button on the sequencing run details page throws an error when click, and the run is not removed.  Reported by @Takadonet 

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Trying to remove a delete a sequencing run.

## Expected behaviour
The sequencing run to be deleted and returned to the listing page.

## Additional context
Additional information to help solve the problem.  Test files, screenshots, IRIDA version information can go here.

**Comment by tom114** [comment]
Completed in #809
