### ISSUE TITLE
Clicking link for remote API in project fails

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#822]
## Describe the bug
In a remote project, attempting to click the link to bring you to the remote API leads to an error:

```
org.thymeleaf.exceptions.TemplateInputException: Error resolving template "remote_apis/remote_api_details", template might not
 exist or might not be accessible by any of the configured Template Resolvers
        at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:870)
        at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607)
...
```

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Setup a remote project.
2. Click the link to view the associated remote API in the project.
3. The error will appear.

## Expected behaviour
I expected to be brought to the remote API page.

## Additional context

The link in the remote project:

![image](https://user-images.githubusercontent.com/200517/95378623-cc005080-08a9-11eb-9f68-1ba43fdd3b08.png)

The error page:

![image](https://user-images.githubusercontent.com/200517/95378675-de7a8a00-08a9-11eb-83d8-93ec43283e54.png)

**Comment by tom114** [comment]
Completed in #823
