### ISSUE TITLE
Title string on Remote IRIDA Connections page for regular users is missing

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#825]
## Describe the bug
The title string for the **Remote IRIDA Connections** page is missing. Instead it is displayed as `??clients.title_en??`.

![image](https://user-images.githubusercontent.com/200517/95628591-fa199800-0a43-11eb-961a-1ed483595d0d.png)

## Steps to reproduce the problem
1. As user with a Manager role (may also occur with other roles) select the **Remote IRIDA Connections** option.

    ![image](https://user-images.githubusercontent.com/200517/95628738-4238ba80-0a44-11eb-804a-a7ec3d2600df.png)

2. The page you are brought to is missing the title string.

## Expected behaviour
I expected the title string to be displayed (instead of `??` string).

## Additional context
None.

**Comment by joshsadam** [comment]
I do not believe that this issue exists anymore since the remote IRIDA connections page now lives inside of the admin panel.  @apetkau can you confirm this for me?
