### ISSUE TITLE
Cannot upload .fastq or fastq.gz to sample

### ISSUE THREAD

**Issue by Takadonet** [phac-nml/irida#827]
## Describe the bug
Attempting to upload thru web browser VERY small fastq's files in either .fastq or fastq.gz file format.

## Steps to reproduce the problem
1. Create a sample
2.  Click **Uploading files** => **Uploading Sequencing Files**
3.  Select files
4. Stuck/Hangs on POST http://irida.com/irida/ajax/samples/##/sequenceFiles/upload

## Expected behaviour
To upload with a free beer for reward

On version 20.09

**Comment by JeffreyThiessen** [comment]
Could not reproduce issue when uploading a small sample. 
Beer functionality is also working as intended, after upload was complete, beer was found in fridge.
