### ISSUE TITLE
Cannot click "Sync Now" on a remote project with status of "Unauthorized"

### ISSUE THREAD

**Issue by tom114** [phac-nml/irida#880]
## Describe the bug
I was trying to synchronize a remote project, but the project sync status was "unauthorized".  After reconnecting I couldn't click the "Sync Now" button

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Went to project sync page
2. Clicked "Sync Now" to sync the project
3. Oauth token was expired, so the status became "Unauthorized"
4. After clicking "Connect" on the remote API, "Sync Now" button was still disabled.  Also disabled after refreshing page.

## Expected behaviour
Sync now button to be re-enabled even in "Unauthorized" state so the new token can be tried again.

## Additional context
N/A

**Comment by deepsidhu85** [comment]
Fixed in #881
