### ISSUE TITLE
Created/Modified dates not visible in project samples table

### ISSUE THREAD

**Issue by tom114** [phac-nml/irida#898]
## Describe the bug
In the 20.09 release (and current development state) the created and modified dates don't display in the project samples table.

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Went to the project samples table
2. Noted the created and modified columns were blank

## Expected behaviour
Expected to see the dates

## Additional context
![image](https://user-images.githubusercontent.com/8951708/103097577-59139580-45cd-11eb-9ff1-cdc7ab245a17.png)

Note the dates show in the line list page so they're still in the DB.

**Comment by deepsidhu85** [comment]
Fixed in #900

**Comment by deepsidhu85** [comment]
Fixed in #900
