### ISSUE TITLE
Allow modifications of parameters for automated pipelines

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#90]
Imported from GitLab issue #474.  Originally posted on 2017/06/21 04:23PM

**Comment by tom114** [comment]
I think this could be increased to also allowing users to specify **any** pipeline to run as an automated pipeline.  I think the best way we could make this work is to reuse the existing "launch pipeline" page to allow a user to set parameters and options for a pipeline they want to run whenever new sequencing data is uploaded.  We could save an `AnalysisSubmissionTemplate` which would be converted to an `AnalysisSubmission` when data is uploaded.

Imported from GitLab.  Originally posted on 2018/02/28 12:57PM

**Comment by tom114** [comment]
Related to #240

**Comment by tom114** [comment]
This will be covered by #240
