### ISSUE TITLE
Vertical scrollbar missing on tabular output (21.01-SNAPSHOT)

### ISSUE THREAD

**Issue by pvanheus** [phac-nml/irida#926]
## Describe the bug
When viewing a tabular (.tsv) file in the Tabular Output viewer, only the first 5 rows are displayed and the vertical scrollbar is not visible. Tested with Firefox (84.0.2) and Chrome (88) on Linux (Ubuntu 20.04).

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Ran M. tuberculosis phylogeny pipeline (https://github.com/COMBAT-TB/irida-pipeline-plugins/tree/master/snippy-tb-sample-iqtree) version 0.1.4
2. Observed Output Files

## Expected behaviour
The dataset has 31 rows, I expect to be able to scroll across all of them.

## Additional context
Screenshot
![image](https://user-images.githubusercontent.com/4154788/106146528-7107a780-617f-11eb-81b1-f63b47aa3087.png)

IRIDA version from development branch built on 26 January 2021 (21.01-SNAPSHOT).

**Comment by tom114** [comment]
Fixed in #933
