### ISSUE TITLE
Login page not displaying

### ISSUE THREAD

**Issue by aknijn** [phac-nml/irida#936]
## Describe the bug
Upon a new installation of the 21.01 version, the application launches but the login page is blank. The localhost_acces_log of tomcat signals a 404 error on the login.bundle.css file which effectively is missing in the dist/css folder.
This happened building from source but the file is also missing in the war package.
Copying the file from the 20.09.5 war file solved the 404 error but the page is still showing up blank.

From the browser console I get this:
Uncaught TypeError: window.translations is not iterable (cannot read property undefined)
    at Object.<anonymous> (i18n.js:23)
    at e (bootstrap:19)
    at Module.<anonymous> (login.bundle.js:2)
    at e (bootstrap:19)
    at bootstrap:83
    at login.bundle.js:2

**Comment by apetkau** [comment]
Thanks for reporting @aknijn . When you were getting the 404 error had you tried doing a hard refresh (Ctrl + F5) or using a private browsing mode to access IRIDA (to make sure older cached files weren't interfering)?

I can see that the `login.bundle.css` file gives a 404 for me, but the login page still displays for IRIDA 21.01.

**Comment by joshsadam** [comment]
This is strange, I also get no issues running a fresh install of 21.01 using a incognito chrome.  The error that you are getting would imply that the internationalization string are not being loaded onto the page properly.  When you load the page open the developer tools in your browser and type `window.translations`  you should see something similar to:

![](https://user-images.githubusercontent.com/11295750/107064908-b80a2400-67a1-11eb-8f9e-dfc8fa2e57c6.png)

**Comment by joshsadam** [comment]
As for the css issue, it seems that webpack is not extracting some of the css into its own files.  It still gets loading onto the page (via injection for javascript).  I am currently working on a new front end build system so hopefully that we will resolved in the next release.

**Comment by aknijn** [comment]
Instead I see this:
![immagine](https://user-images.githubusercontent.com/23658466/107081686-5ecae080-67f3-11eb-89e1-75c97cfa1fe8.png)

**Comment by joshsadam** [comment]
@aknijn are you using a custom login page?

**Comment by aknijn** [comment]
No, I just compiled the code and launched the war package

**Comment by joshsadam** [comment]
Really raking my brain to figure out what is going on here, I have not been able to reproduce it.  Can you confirm for me that you have run `yarn build` and that there are files within `src/main/webapp/pages/templates/i18n`?

**Comment by aknijn** [comment]
I did not run `yarn build` and the only file within `src/main/webapp/pages/templates/i18n` is README.md so that seems to be the problem. Did I miss this somewhere? Thank you very much for your assistance!

**Comment by joshsadam** [comment]
You're welcome. Sorry I need to pick up my kids from school. I will try to help out more next week. Did the login page load after you did the yarn build?

**Comment by aknijn** [comment]
No it did not, the directory was still empty and the page blank. And I think the `mvn install` comand might already have executed `yarn build`? I do have to say I am building on a Windows machine and maybe that could be a problem (for version 19.01 it was not but it might now). Tomorrow I will try on debian to see if that changes something.

**Comment by aknijn** [comment]
So building on debian solved the problem! That will teach me! So sorry for the inconvenience.
Compliments on the work you did, the first impression of this new version is really great! We will use IRIDA for SARS-CoV-2 variant surveillance and the 19.01 version was missing some important features you have introduced in newer versions (like upload of fasta and fast5 files). I will have to figure out how to apply the changes I made before but integrating our pipelines should be easier now. Thanks again, Arnold

**Comment by joshsadam** [comment]
We will need to look an see why that is not building specifically on windows (I have a feeling it is something that I particularly wrote :().  Thank you for the kind words on the release, the team has spent a lot of time trying to get feature packed.  I am going to close this issue for now. It you have more problems please let us know.
