### ISSUE TITLE
“TypeError: can't convert undefined to object” in Advanced Visualisation - 

### ISSUE THREAD

**Issue by zipho** [phac-nml/irida#941]
## Describe the bug

When I added metadata/linelist on my samples.

The advanced visualisation page hangs on load with an error from the browser console.

“TypeError: can't convert undefined to object” 

It was only later when I realise that it only occurs when the reference used to construct the newick tree has anything other than `>reference` at the first line.

For my mtb pipeline mine had `>Chromosome` and sometimes `>NC_000962.3`. 

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Run a phylogeny pipeline on IRIDA
2. Upon results Viewed Results 
3. Clicked on Advanced Visualisation

## Expected behaviour
For my phylogeny tree to be visible with metadata.
![Screenshot from 2021-02-13 08-42-46](https://user-images.githubusercontent.com/2108971/107843891-96c7ba00-6dd7-11eb-968a-96c23a839fcb.png)

## Additional context
Latest IRIDA

**Comment by tom114** [comment]
Fixed in #941
