### ISSUE TITLE
Increase documentation on pipeline development/tool development for Galaxy

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#95]
Imported from GitLab issue #484.  Originally posted on 2017/06/22 11:54AM

**Comment by tom114** [comment]
This may become just a review issue.  We'll have Jen, Peter, Dan, or Matt go through a pipeline development process and see what needs to be enhanced.  Leaving open for now.

Imported from GitLab.  Originally posted on 2017/11/09 02:10PM

**Comment by tom114** [comment]
This has been covered by the pipeline plugin functions.  See https://github.com/phac-nml/irida-plugin-example
