### ISSUE TITLE
Rework flow of analysis details page

### ISSUE THREAD

**Issue by joshsadam** [phac-nml/irida#98]
- [x] Move the advanced phylogenetic visualization to replace preview
- [x] Remove angular-ui-router - simplify this page.
- [x] Clean up templates so they are not just one big file.

This addresses issues spoken offline about !1030 with @thomas.matthews

Imported from GitLab issue #489.  Originally posted on 2017/06/26 11:42AM

**Comment by tom114** [comment]
Related to #82
