### ISSUE TITLE
Mark one set of sequence reads as the "default" in a sample

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#980]
## Describe your idea for a new feature
In IRIDA it's possible to upload multiple sets of sequence read files to the same sample:
![image](https://user-images.githubusercontent.com/200517/114648539-a747c400-9ca4-11eb-820a-67256371d8d2.png)

There's many places, however, where it only really makes sense to work with one of those sets of files, such as running a pipeline:
![image](https://user-images.githubusercontent.com/200517/114648832-11606900-9ca5-11eb-9a30-423322ff0103.png)

or uploading files to Galaxy:

![image](https://user-images.githubusercontent.com/200517/114649028-60a69980-9ca5-11eb-8da5-cffbc139a7ca.png)

Three solutions to deal with this is either to (1) concatenate the sequence reads, or (2) delete all but one set of reads, (3) select the specific set of sequence files to use when e.g., running a pipeline. However, sometimes none of those solutions make sense (e.g., 1 and 2 may not work if users don't want to modify/remove sequence data, and 3 requires people to select the correct files each time they are working with them).

It might also be useful to offer an additional solution (4) mark one set of sequence reads as the "default" which gets selected automatically when running a pipeline (or which gets selected automatically when exporting to a Galaxy history). This leaves the other sets of files available if needed.

## Describe how you would access this feature?
From the sequence files page users could set one set of sequence reads as the "default" one for a sample. Then, when selecting samples (and sequence reads) to run through a pipeline, the default is always selected (thus users don't have to spend time making sure the correct set of reads are selected). Additionally, when exporting data to Galaxy, the default set of reads are the ones that get exported (or this could be configurable with an option in IRIDA).

## Additional information
None.

**Comment by deepsidhu85** [comment]
This is being done as a part of the Sample Details page refactor that I have been working on. It won't get out into this release but should be out for the next one

**Comment by deepsidhu85** [comment]
Fixed in #1370
